(in-package "MORPHIX")


;; lex-entries for irregular-verbs
;; 2
(l-s "brenn" '(214100 (VGFC C4 . "brannte") (PPRF . "gebrannt")))
(l-s "brannte" '((STAMM "brenn" . VGFC)))
(l-s "brann" '((STAMM "brenn" . PPRF)))
(l-s "kenn" '(214100 (VGFC C4 . "kannte") (PPRF . "gekannt")))
(l-s "kannte" '((STAMM "kenn" . VGFC)))
(l-s "kann" '((STAMM "kenn" . PPRF)))
(l-s "renn" '(214000 (VGFC C4 . "rannte") (PPRF . "gerannt")))
(l-s "rannte" '((STAMM "renn" . VGFC)))
(l-s "rann" '((STAMM "renn" . PPRF)))
(l-s "nenn" '(214100 (VGFC C4 . "nannte") (PPRF . "genannt")))
(l-s "nannte" '((STAMM "nenn" . VGFC)))
(l-s "nann" '((STAMM "nenn" . PPRF)))
(l-s "send" '(226100 (VGFC C4 . "sandte") (PPRF . "gesandt")))
(l-s "sandte" '((STAMM "send" . VGFC)))
(l-s "sand" '((STAMM "send" . PPRF)))
(l-s "wend" '(226100 (VGFC C4 . "wandte") (PPRF . "gewandt")))
(l-s "wandte" '((STAMM "wend" . VGFC)))
(l-s "wand" '((STAMM "wend" . PPRF)))

;; 3

(l-s "beiss" '(251100 (VGFC C2 . "biss") (PPRF . "gebissen")))
(l-s "biss" '((STAMM "beiss" . VGFC)))
(l-s "bleib" '(215000 (VGFC C1 . "blieb") (PPRF . "geblieben")))
(l-s "blieb" '((STAMM "bleib" . VGFC)))
(l-s "bleich" '(215100 (VGFC C1 . "blich") (PPRF . "geblichen")))
(l-s "blich" '((STAMM "bleich" . VGFC)))
(l-s "duenk" '(215100 (VGFC C4 . "deuchte") (PPRF . "gedeucht")))
(l-s "deuchte" '((STAMM "duenk" . VGFC)))
(l-s "deuch" '((STAMM "duenk" . PPRF)))
(l-s "gedeih" '(215000 (VGFC C1 . "gedieh") (PPRF . "gediehen")))
(l-s "gedieh" '((STAMM "gedeih" . VGFC)))
(l-s "geh" '(215000 (VGFC C1 . "ging") (PPRF . "gegangen")))
(l-s "ging" '((STAMM "geh" . VGFC)))
(l-s "gang" '((STAMM "geh" . PPRF)))
(l-s "gleich" '(215100 (VGFC C1 . "glich") (PPRF . "geglichen")))
(l-s "glich" '((STAMM "gleich" . VGFC)))
(l-s "gleit" '(227000 (VGFC C3 . "glitt") (PPRF . "geglitten")))
(l-s "glitt" '((STAMM "gleit" . VGFC)))
(l-s "greif" '(215100 (VGFC C1 . "griff") (PPRF . "gegriffen")))
(l-s "griff" '((STAMM "greif" . VGFC)))
(l-s "hau" '(215100 (VGFC C1 . "hieb") (PPRF . "gehauen")))
(l-s "hieb" '((STAMM "hau" . VGFC)))
(l-s "heiss" '(251100 (VGFC C2 . "hiess") (PPRF . "geheissen")))
(l-s "hiess" '((STAMM "heiss" . VGFC)))
(l-s "haeng" '(215100 (VGFC C1 . "hing") (PPRF . "gehangen")))
(l-s "hing" '((STAMM "haeng" . VGFC)))
(l-s "hang" '((STAMM "haeng" . PPRF)))
(l-s "kneif" '(215100 (VGFC C1 . "kniff") (PPRF . "gekniffen")))
(l-s "kniff" '((STAMM "kneif" . VGFC)))
(l-s "leid" '(227100 (VGFC C3 . "litt") (PPRF . "gelitten")))
(l-s "litt" '((STAMM "leid" . VGFC)))
(l-s "leih" '(215100 (VGFC C1 . "lieh") (PPRF . "geliehen")))
(l-s "lieh" '((STAMM "leih" . VGFC)))
(l-s "meid" '(227100 (VGFC C3 . "mied") (PPRF . "gemieden")))
(l-s "mied" '((STAMM "meid" . VGFC)))
(l-s "pfeif" '(215100 (VGFC C1 . "pfiff") (PPRF . "gepfiffen")))
(l-s "pfiff" '((STAMM "pfeif" . VGFC)))
(l-s "preis" '(251100 (VGFC C2 . "pries") (PPRF . "gepriesen")))
(l-s "pries" '((STAMM "preis" . VGFC)))
(l-s "reib" '(215100 (VGFC C1 . "rieb") (PPRF . "gerieben")))
(l-s "rieb" '((STAMM "reib" . VGFC)))
(l-s "reiss" '(251100 (VGFC C2 . "riss") (PPRF . "gerissen")))
(l-s "riss" '((STAMM "reiss" . VGFC)))
(l-s "reit" '(227000 (VGFC C3 . "ritt") (PPRF . "geritten")))
(l-s "ritt" '((STAMM "reit" . VGFC)))
(l-s "ruf" '(215100 (VGFC C1 . "rief") (PPRF . "gerufen")))
(l-s "rief" '((STAMM "ruf" . VGFC)))
(l-s "scheid" '(227100 (VGFC C3 . "schied") (PPRF . "geschieden")))
(l-s "schied" '((STAMM "scheid" . VGFC)))
(l-s "schein" '(215100 (VGFC C1 . "schien") (PPRF . "geschienen")))
(l-s "schien" '((STAMM "schein" . VGFC)))
(l-s "schleich" '(215000 (VGFC C1 . "schlich") (PPRF . "geschlichen")))
(l-s "schlich" '((STAMM "schleich" . VGFC)))
(l-s "schleif" '(215100 (VGFC C1 . "schliff") (PPRF . "geschliffen")))
(l-s "schliff" '((STAMM "schleif" . VGFC)))
(l-s "schneid" '(227100 (VGFC C3 . "schnitt") (PPRF . "geschnitten")))
(l-s "schnitt" '((STAMM "schneid" . VGFC)))
(l-s "schrei" '(215100 (VGFC C4 . "schrie") (PPRF . "geschrien")))
(l-s "schrie" '((STAMM "schrei" . VGFC)))
(l-s "schreib" '(215100 (VGFC C1 . "schrieb") (PPRF . "geschrieben")))
(l-s "schrieb" '((STAMM "schreib" . VGFC)))
(l-s "schreit" '(227000 (VGFC C3 . "schritt") (PPRF . "geschritten")))
(l-s "schritt" '((STAMM "schreit" . VGFC)))
(l-s "schweig" '(215100 (VGFC C1 . "schwieg") (PPRF . "geschwiegen")))
(l-s "schwieg" '((STAMM "schweig" . VGFC)))
(l-s "spei" '(215100 (VGFC C4 . "spie") (PPRF . "gespien")))
(l-s "spie" '((STAMM "spei" . VGFC)))
(l-s "spleiss" '(251100 (VGFC C2 . "spliss") (PPRF . "gesplissen")))
(l-s "spliss" '((STAMM "spleiss" . VGFC)))
(l-s "steig" '(215000 (VGFC C1 . "stieg") (PPRF . "gestiegen")))
(l-s "stieg" '((STAMM "steig" . VGFC)))
(l-s "streich" '(215100 (VGFC C1 . "strich") (PPRF . "gestrichen")))
(l-s "strich" '((STAMM "streich" . VGFC)))
(l-s "streit" '(227100 (VGFC C3 . "stritt") (PPRF . "gestritten")))
(l-s "stritt" '((STAMM "streit" . VGFC)))
(l-s "treib" '(215100 (VGFC C1 . "trieb") (PPRF . "getrieben")))
(l-s "trieb" '((STAMM "treib" . VGFC)))
(l-s "weich" '(215000 (VGFC C1 . "wich") (PPRF . "gewichen")))
(l-s "wich" '((STAMM "weich" . VGFC)))
(l-s "weis" '(251100 (VGFC C2 . "wies") (PPRF . "gewiesen")))
(l-s "wies" '((STAMM "weis" . VGFC)))
(l-s "zeih" '(215100 (VGFC C1 . "zieh") (PPRF . "geziehen")))
(l-s "zieh" '((STAMM "zeih" . VGFC)))

;; 4

(l-s "beginn" '(216100 (VGFC C1 . "begann") (VGFD . "begaenne") (PPRF . "begonnen")))
(l-s "begaenne" '((STAMM "beginn" . VGFD)))
(l-s "begann" '((STAMM "beginn" . VGFC)))
(l-s "begonn" '((STAMM "beginn" . PPRF)))
(l-s "beweg" '(216100 (VGFC C1 . "bewog") (VGFD . "bewoege") (PPRF . "bewogen")))
(l-s "bewoege" '((STAMM "beweg" . VGFD)))
(l-s "bewog" '((STAMM "beweg" . VGFC)))
(l-s "beweg" '(213100 (PPRF . "bewegt")))
(l-s "bieg" '(216100 (VGFC C1 . "bog") (VGFD . "boege") (PPRF . "gebogen")))
(l-s "boege" '((STAMM "bieg" . VGFD)))
(l-s "bog" '((STAMM "bieg" . VGFC)))
(l-s "biet" '(228100 (VGFC C3 . "bot") (VGFD . "boete") (PPRF . "geboten")))
(l-s "boete" '((STAMM "biet" . VGFD)))
(l-s "bot" '((STAMM "biet" . VGFC)))
(l-s "bind" '(228100 (VGFC C3 . "band") (VGFD . "baende") (PPRF . "gebunden")))
(l-s "baende" '((STAMM "bind" . VGFD)))
(l-s "band" '((STAMM "bind" . VGFC)))
(l-s "bund" '((STAMM "bind" . PPRF)))
(l-s "bitt" '(228100 (VGFC C3 . "bat") (VGFD . "baete") (PPRF . "gebeten")))
(l-s "baete" '((STAMM "bitt" . VGFD)))
(l-s "bat" '((STAMM "bitt" . VGFC)))
(l-s "bet" '((STAMM "bitt" . PPRF)))
(l-s "bring" '(216100 (VGFC C4 . "brachte") (VGFD . "braechte") (PPRF . "gebracht")))
(l-s "braechte" '((STAMM "bring" . VGFD)))
(l-s "brachte" '((STAMM "bring" . VGFC)))
(l-s "brach" '((STAMM "bring" . PPRF)))
(l-s "denk" '(216100 (VGFC C4 . "dachte") (VGFD . "daechte") (PPRF . "gedacht")))
(l-s "daechte" '((STAMM "denk" . VGFD)))
(l-s "dachte" '((STAMM "denk" . VGFC)))
(l-s "dach" '((STAMM "denk" . PPRF)))
(l-s "ding" '(216100 (VGFC C1 . "dang") (VGFD . "daenge") (PPRF . "gedungen")))
(l-s "daenge" '((STAMM "ding" . VGFD)))
(l-s "dang" '((STAMM "ding" . VGFC)))
(l-s "dung" '((STAMM "ding" . PPRF)))
(l-s "dring" '(216000 (VGFC C1 . "drang") (VGFD . "draenge") (PPRF . "gedrungen")))
(l-s "draenge" '((STAMM "dring" . VGFD)))
(l-s "drang" '((STAMM "dring" . VGFC)))
(l-s "drung" '((STAMM "dring" . PPRF)))
(l-s "erkies" '(252100 (VGFC C1 . "erkor") (VGFD . "erkoere") (PPRF . "erkoren")))
(l-s "erkoere" '((STAMM "erkies" . VGFD)))
(l-s "erkor" '((STAMM "erkies" . VGFC)))
(l-s "find" '(228100 (VGFC C3 . "fand") (VGFD . "faende") (PPRF . "gefunden")))
(l-s "faende" '((STAMM "find" . VGFD)))
(l-s "fand" '((STAMM "find" . VGFC)))
(l-s "fund" '((STAMM "find" . PPRF)))
(l-s "flieg" '(216000 (VGFC C1 . "flog") (VGFD . "floege") (PPRF . "geflogen")))
(l-s "floege" '((STAMM "flieg" . VGFD)))
(l-s "flog" '((STAMM "flieg" . VGFC)))
(l-s "flieh" '(216000 (VGFC C1 . "floh") (VGFD . "floehe") (PPRF . "geflohen")))
(l-s "floehe" '((STAMM "flieh" . VGFD)))
(l-s "floh" '((STAMM "flieh" . VGFC)))
(l-s "fliess" '(252000 (VGFC C2 . "floss") (VGFD . "floesse") (PPRF . "geflossen")))
(l-s "floesse" '((STAMM "fliess" . VGFD)))
(l-s "floss" '((STAMM "fliess" . VGFC)))
(l-s "frier" '(216100 (VGFC C1 . "fror") (VGFD . "froere") (PPRF . "gefroren")))
(l-s "froere" '((STAMM "frier" . VGFD)))
(l-s "fror" '((STAMM "frier" . VGFC)))
(l-s "gaer" '(216100 (VGFC C1 . "gor") (VGFD . "goere") (PPRF . "gegoren")))
(l-s "goere" '((STAMM "gaer" . VGFD)))
(l-s "gor" '((STAMM "gaer" . VGFC)))
(l-s "geling" '(216000 (VGFC C1 . "gelang") (VGFD . "gelaenge") (PPRF . "gelungen")))
(l-s "gelaenge" '((STAMM "geling" . VGFD)))
(l-s "gelang" '((STAMM "geling" . VGFC)))
(l-s "gelung" '((STAMM "geling" . PPRF)))
(l-s "genes" '(252000 (VGFC C2 . "genas") (VGFD . "genaese") (PPRF . "genesen")))
(l-s "genaese" '((STAMM "genes" . VGFD)))
(l-s "genas" '((STAMM "genes" . VGFC)))
(l-s "geniess" '(252100 (VGFC C2 . "genoss") (VGFD . "genoesse") (PPRF . "genossen")))
(l-s "genoesse" '((STAMM "geniess" . VGFD)))
(l-s "genoss" '((STAMM "geniess" . VGFC)))
(l-s "gewinn" '(216100 (VGFC C1 . "gewann") (VGFD . "gewaenne") (PPRF . "gewonnen")))
(l-s "gewaenne" '((STAMM "gewinn" . VGFD)))
(l-s "gewann" '((STAMM "gewinn" . VGFC)))
(l-s "gewonn" '((STAMM "gewinn" . VGFC)))
(l-s "giess" '(252100 (VGFC C2 . "goss") (VGFD . "goesse") (PPRF . "gegossen")))
(l-s "goesse" '((STAMM "giess" . VGFD)))
(l-s "goss" '((STAMM "giess" . VGFC)))
(l-s "glimm" '(216100 (VGFC C1 . "glomm") (VGFD . "gloemme") (PPRF . "geglommen")))
(l-s "gloemme" '((STAMM "glimm" . VGFD)))
(l-s "glomm" '((STAMM "glimm" . VGFC)))
(l-s "heb" '(216100 (VGFC C1 . "hob") (VGFD . "hoebe") (PPRF . "gehoben")))
(l-s "hoebe" '((STAMM "heb" . VGFD)))
(l-s "hob" '((STAMM "heb" . VGFC)))
(l-s "klimm" '(216000 (VGFC C1 . "klomm") (VGFD . "kloemme") (PPRF . "geklommen")))
(l-s "kloemme" '((STAMM "klimm" . VGFD)))
(l-s "klomm" '((STAMM "klimm" . VGFC)))
(l-s "kling" '(216100 (VGFC C1 . "klang") (VGFD . "klaenge") (PPRF . "geklungen")))
(l-s "klaenge" '((STAMM "kling" . VGFD)))
(l-s "klang" '((STAMM "kling" . VGFC)))
(l-s "klung" '((STAMM "kling" . PPRF)))
(l-s "komm" '(216000 (VGFC C1 . "kam") (VGFD . "kaeme") (PPRF . "gekommen")))
(l-s "kaeme" '((STAMM "komm" . VGFD)))
(l-s "kam" '((STAMM "komm" . VGFC)))
(l-s "kriech" '(216000 (VGFC C1 . "kroch") (VGFD . "kroeche") (PPRF . "gekrochen")))
(l-s "kroeche" '((STAMM "kriech" . VGFD)))
(l-s "kroch" '((STAMM "kriech" . VGFC)))
(l-s "kuer" '(213100 (PPRF . "gekuert")))
(l-s "kuer" '(216100 (VGFC C1 . "kor") (VGFD . "koere") (PPRF . "gekoren")))
(l-s "koere" '((STAMM "kuer" . VGFD)))
(l-s "kor" '((STAMM "kuer" . VGFC)))
(l-s "lieg" '(216100 (VGFC C1 . "lag") (VGFD . "laege") (PPRF . "gelegen")))
(l-s "laege" '((STAMM "lieg" . VGFD)))
(l-s "lag" '((STAMM "lieg" . VGFC)))
(l-s "leg" '((STAMM "lieg" . PPRF)))
(l-s "leg" '(213100 (PPRF . "gelegt")))
(l-s "lueg" '(216100 (VGFC C1 . "log") (VGFD . "loege") (PPRF . "gelogen")))
(l-s "loege" '((STAMM "lueg" . VGFD)))
(l-s "log" '((STAMM "lueg" . VGFC)))
(l-s "missling" '(216000 (VGFC C1 . "misslang") (VGFD . "misslaenge") (PPRF . "misslungen")))
(l-s "misslaenge" '((STAMM "missling" . VGFD)))
(l-s "misslang" '((STAMM "missling" . VGFC)))
(l-s "misslung" '((STAMM "missling" . PPRF)))
(l-s "pfleg" '(216100 (VGFC C1 . "pflog") (VGFD . "pfloege") (PPRF . "gepflogen")))
(l-s "pfloege" '((STAMM "pfleg" . VGFD)))
(l-s "pflog" '((STAMM "pfleg" . VGFC)))
(l-s "pfleg" '(213100 (PPRF . "gepflegt")))
(l-s "riech" '(216100 (VGFC C1 . "roch") (VGFD . "roeche") (PPRF . "gerochen")))
(l-s "roeche" '((STAMM "riech" . VGFD)))
(l-s "roch" '((STAMM "riech" . VGFC)))
(l-s "ring" '(216100 (VGFC C1 . "rang") (VGFD . "raenge") (PPRF . "gerungen")))
(l-s "raenge" '((STAMM "ring" . VGFD)))
(l-s "rang" '((STAMM "ring" . VGFC)))
(l-s "rung" '((STAMM "ring" . PPRF)))
(l-s "rinn" '(216000 (VGFC C1 . "rann") (VGFD . "raenne") (PPRF . "geronnen")))
(l-s "raenne" '((STAMM "rinn" . VGFD)))
(l-s "rann" '((STAMM "rinn" . VGFC)))
(l-s "ronn" '((STAMM "rinn" . PPRF)))
(l-s "saug" '(216100 (VGFC C1 . "sog") (VGFD . "soege") (PPRF . "gesogen")))
(l-s "soege" '((STAMM "saug" . VGFD)))
(l-s "sog" '((STAMM "saug" . VGFC)))
(l-s "saug" '(213100 (PPRF . "gesaugt")))
(l-s "schall" '(216100 (VGFC C1 . "scholl") (VGFD . "schoelle") (PPRF . "geschallt")))
(l-s "schoelle" '((STAMM "schall" . VGFD)))
(l-s "scholl" '((STAMM "schall" . VGFC)))
(l-s "schall" '(213100 (PPRF . "geschallt")))
(l-s "schaff" '(216100 (VGFC C1 . "schuf") (VGFD . "schuefe") (PPRF . "geschaffen")))
(l-s "schuefe" '((STAMM "schaff" . VGFD)))
(l-s "schuf" '((STAMM "schaff" . VGFC)))
(l-s "schaff" '(213100 (PPRF . "geschafft")))
(l-s "scher" '(216100 (VGFC C1 . "schor") (VGFD . "schoere") (PPRF . "geschoren")))
(l-s "schoere" '((STAMM "scher" . VGFD)))
(l-s "schor" '((STAMM "scher" . VGFC)))
(l-s "scher" '(213100 (PPRF . "geschert")))
(l-s "schieb" '(216100 (VGFC C1 . "schob") (VGFD . "schoebe") (PPRF . "geschoben")))
(l-s "schoebe" '((STAMM "schieb" . VGFD)))
(l-s "schob" '((STAMM "schieb" . VGFC)))
(l-s "schiess" '(252100 (VGFC C2 . "schoss") (VGFD . "schoesse") (PPRF . "geschossen")))
(l-s "schoesse" '((STAMM "schiess" . VGFD)))
(l-s "schoss" '((STAMM "schiess" . VGFC)))
(l-s "schind" '(228100 (VGFC C3 . "schund") (VGFD . "schuende") (PPRF . "geschunden")))
(l-s "schuende" '((STAMM "schind" . VGFD)))
(l-s "schund" '((STAMM "schind" . VGFC)))
(l-s "schind" '(225100 (PPRF . "geschunden")))
(l-s "schliess" '(252100 (VGFC C2 . "schloss") (VGFD . "schloesse") (PPRF . "geschlossen")))
(l-s "schloesse" '((STAMM "schliess" . VGFD)))
(l-s "schloss" '((STAMM "schliess" . VGFC)))
(l-s "schling" '(216100 (VGFC C1 . "schlang") (VGFD . "schlaenge") (PPRF . "geschlungen")))
(l-s "schlaenge" '((STAMM "schling" . VGFD)))
(l-s "schlang" '((STAMM "schling" . VGFC)))
(l-s "schlung" '((STAMM "schling" . PPRF)))
(l-s "schnaub" '(216100 (VGFC C1 . "schnob") (VGFD . "schnoebe") (PPRF . "geschnoben")))
(l-s "schnoebe" '((STAMM "schnaub" . VGFD)))
(l-s "schnob" '((STAMM "schnaub" . VGFC)))
(l-s "schnaub" '(213100 (PPRF . "geschnaubt")))
(l-s "schwimm" '(216000 (VGFC C1 . "schwamm") (VGFD . "schwoemme") (PPRF . "geschwommen")))
(l-s "schwoemme" '((STAMM "schwimm" . VGFD)))
(l-s "schwaemme" '((STAMM "schwimm" . VGFD)))
(l-s "schwamm" '((STAMM "schwimm" . VGFC)))
(l-s "schwomm" '((STAMM "schwimm" . PPRF)))
(l-s "schwind" '(228000 (VGFC C3 . "schwand") (VGFD . "schwaende") (PPRF . "geschwunden")))
(l-s "schwaende" '((STAMM "schwind" . VGFD)))
(l-s "schwand" '((STAMM "schwind" . VGFC)))
(l-s "schwund" '((STAMM "schwind" . PPRF)))
(l-s "schwing" '(216100 (VGFC C1 . "schwang") (VGFD . "schwaenge") (PPRF . "geschwungen")))
(l-s "schwaenge" '((STAMM "schwing" . VGFD)))
(l-s "schwang" '((STAMM "schwing" . VGFC)))
(l-s "schwung" '((STAMM "schwing" . PPRF)))
(l-s "schwoer" '(216100 (VGFC C1 . "schwor") (VGFD . "schwuere") (PPRF . "geschworen")))
(l-s "schwuere" '((STAMM "schwoer" . VGFD)))
(l-s "schwor" '((STAMM "schwoer" . VGFC)))
(l-s "sied" '(228100 (VGFC C3 . "sott") (VGFD . "soette") (PPRF . "gesotten")))
(l-s "soette" '((STAMM "sied" . VGFD)))
(l-s "sott" '((STAMM "sied" . VGFC)))
(l-s "sied" '(225100 (PPRF . "gesiedet")))
(l-s "sing" '(216100 (VGFC C1 . "sang") (VGFD . "saenge") (PPRF . "gesungen")))
(l-s "saenge" '((STAMM "sing" . VGFD)))
(l-s "sang" '((STAMM "sing" . VGFC)))
(l-s "sung" '((STAMM "sing" . PPRF)))
(l-s "sink" '(216000 (VGFC C1 . "sank") (VGFD . "saenke") (PPRF . "gesunken")))
(l-s "saenke" '((STAMM "sink" . VGFD)))
(l-s "sank" '((STAMM "sink" . VGFC)))
(l-s "sunk" '((STAMM "sink" . PPRF)))
(l-s "sinn" '(216100 (VGFC C1 . "sann") (VGFD . "saenne") (PPRF . "gesonnen")))
(l-s "saenne" '((STAMM "sinn" . VGFD)))
(l-s "sann" '((STAMM "sinn" . VGFC)))
(l-s "sonn" '((STAMM "sinn" . PPRF)))
(l-s "sitz" '(252100 (VGFC C2 . "sass") (VGFD . "saesse") (PPRF . "gesessen")))
(l-s "saesse" '((STAMM "sitz" . VGFD)))
(l-s "sass" '((STAMM "sitz" . VGFC)))
(l-s "sess" '((STAMM "sitz" . PPRF)))
(l-s "spinn" '(216100 (VGFC C1 . "spann") (VGFD . "spoenne") (PPRF . "gesponnen")))
(l-s "spoenne" '((STAMM "spinn" . VGFD)))
(l-s "spann" '((STAMM "spinn" . VGFC)))
(l-s "sponn" '((STAMM "spinn" . PPRF)))
(l-s "spriess" '(252000 (VGFC C2 . "spross") (VGFD . "sproesse") (PPRF . "gesprossen")))
(l-s "sproesse" '((STAMM "spriess" . VGFD)))
(l-s "spross" '((STAMM "spriess" . VGFC)))
(l-s "spring" '(216000 (VGFC C1 . "sprang") (VGFD . "spraenge") (PPRF . "gesprungen")))
(l-s "spraenge" '((STAMM "spring" . VGFD)))
(l-s "sprang" '((STAMM "spring" . VGFC)))
(l-s "sprung" '((STAMM "spring" . PPRF)))
(l-s "steck" '(216100 (VGFC C1 . "stak") (VGFD . "staeke") (PPRF . "gesteckt")))
(l-s "staeke" '((STAMM "steck" . VGFD)))
(l-s "stak" '((STAMM "steck" . VGFC)))
(l-s "steck" '(213100 (PPRF . "gesteckt")))
(l-s "steh" '(216100 (VGFC C3 . "stand") (VGFD . "stuende") (PPRF . "gestanden")))
(l-s "stuende" '((STAMM "steh" . VGFD)))
(l-s "stand" '((STAMM "steh" . VGFC)))
(l-s "stieb" '(216100 (VGFC C1 . "stob") (VGFD . "stoebe") (PPRF . "gestoben")))
(l-s "stoebe" '((STAMM "stieb" . VGFD)))
(l-s "stob" '((STAMM "stieb" . VGFC)))
(l-s "stieb" '(213100 (PPRF . "gestiebt")))
(l-s "stink" '(216100 (VGFC C1 . "stank") (VGFD . "staenke") (PPRF . "gestunken")))
(l-s "staenke" '((STAMM "stink" . VGFD)))
(l-s "stank" '((STAMM "stink" . VGFC)))
(l-s "stunk" '((STAMM "stink" . PPRF)))
(L-S "wink" '(213100 (PPRF . "gewunken")))
(l-s "wunk" '((STAMM "wink" . PPRF)))
(l-s "trief" '(216100 (VGFC C1 . "troff") (VGFD . "troeffe") (PPRF . "getroffen")))
(l-s "troeffe" '((STAMM "trief" . VGFD)))
(l-s "troff" '((STAMM "trief" . VGFC)))
(l-s "trief" '(213100 (PPRF . "getrieft")))
(l-s "trink" '(216100 (VGFC C1 . "trank") (VGFD . "traenke") (PPRF . "getrunken")))
(l-s "traenke" '((STAMM "trink" . VGFD)))
(l-s "trank" '((STAMM "trink" . VGFC)))
(l-s "trunk" '((STAMM "trink" . PPRF)))
(l-s "trueg" '(216100 (VGFC C1 . "trog") (VGFD . "troege") (PPRF . "getrogen")))
(l-s "troege" '((STAMM "trueg" . VGFD)))
(l-s "trog" '((STAMM "trueg" . VGFC)))
(l-s "tu" '(288100 (VGFC C3 . "tat") (VGFD . "taete") (PPRF . "getan")))
(l-s "taete" '((STAMM "tu" . VGFD)))
(l-s "tat" '((STAMM "tu" . VGFC)))
(l-s "ta" '((STAMM "tu" . PPRF)))
(l-s "verdriess" '(252100 (VGFC C2 . "verdross") (VGFD . "verdroesse") (PPRF . "verdrossen")))
(l-s "verdroesse" '((STAMM "verdriess" . VGFD)))
(l-s "verdross" '((STAMM "verdriess" . VGFC)))
(l-s "verlier" '(216100 (VGFC C1 . "verlor") (VGFD . "verloere") (PPRF . "verloren")))
(l-s "verloere" '((STAMM "verlier" . VGFD)))
(l-s "verlor" '((STAMM "verlier" . VGFC)))
(l-s "waeg" '(216100 (VGFC C1 . "wog") (VGFD . "woege") (PPRF . "gewogen")))
(l-s "woege" '((STAMM "waeg" . VGFD)))
(l-s "wog" '((STAMM "waeg" . VGFC)))
(l-s "waeg" '(213100 (PPRF . "gewaegt")))
(l-s "wieg" '(216100 (VGFC C1 . "wog") (VGFD . "woege") (PPRF . "gewogen")))
(l-s "woege" '((STAMM "wieg" . VGFD)))
(l-s "wog" '((STAMM "wieg" . VGFC)))
(l-s "wieg" '(213100 (PPRF . "gewiegt")))
(l-s "web" '(216100 (VGFC C1 . "wob") (VGFD . "woebe") (PPRF . "gewoben")))
(l-s "woebe" '((STAMM "web" . VGFD)))
(l-s "wob" '((STAMM "web" . VGFC)))
(l-s "web" '(213100 (PPRF . "gewebt")))
(l-s "wind" '(228100 (VGFC C3 . "wand") (VGFD . "waende") (PPRF . "gewunden")))
(l-s "waende" '((STAMM "wind" . VGFD)))
(l-s "wand" '((STAMM "wind" . VGFC)))
(l-s "wund" '((STAMM "wind" . PPRF)))
(l-s "wring" '(216100 (VGFC C1 . "wrang") (VGFD . "wraenge") (PPRF . "gewrungen")))
(l-s "wraenge" '((STAMM "wring" . VGFD)))
(l-s "wrang" '((STAMM "wring" . VGFC)))
(l-s "wrung" '((STAMM "wring" . PPRF)))
(l-s "zieh" '(216100 (VGFC C1 . "zog") (VGFD . "zoege") (PPRF . "gezogen")))
(l-s "zoege" '((STAMM "zieh" . VGFD)))
(l-s "zog" '((STAMM "zieh" . VGFC)))
(l-s "zwing" '(216100 (VGFC C1 . "zwang") (VGFD . "zwaenge") (PPRF . "gezwungen")))
(l-s "zwaenge" '((STAMM "zwing" . VGFD)))
(l-s "zwang" '((STAMM "zwing" . VGFC)))
(l-s "zwung" '((STAMM "zwing" . PPRF)))

;; 5

(l-s "blas" '(253100 (VGFB B2 . "blaest") (VGFC C2 . "blies") (PPRF . "geblasen")))
(l-s "blaest" '((STAMM "blas" . VGFB)))
(l-s "blies" '((STAMM "blas" . VGFC)))
(l-s "brat" '(229100 (VGFB B3 . "braet") (VGFC C3 . "briet") (PPRF . "gebraten")))
(l-s "braet" '((STAMM "brat" . VGFB)))
(l-s "briet" '((STAMM "brat" . VGFC)))
(l-s "fall" '(217000 (VGFB B1 . "faell") (VGFC C1 . "fiel") (PPRF . "gefallen")))
(l-s "faell" '((STAMM "fall" . VGFB)))
(l-s "fiel" '((STAMM "fall" . VGFC)))
(l-s "fang" '(217100 (VGFB B1 . "faeng") (VGFC C1 . "fing") (PPRF . "gefangen")))
(l-s "faeng" '((STAMM "fang" . VGFB)))
(l-s "fing" '((STAMM "fang" . VGFC)))
(l-s "halt" '(229100 (VGFB B3 . "haelt") (VGFC C3 . "hielt") (PPRF . "gehalten")))
(l-s "haelt" '((STAMM "halt" . VGFB)))
(l-s "hielt" '((STAMM "halt" . VGFC)))
(l-s "lass" '(253100 (VGFB B2 . "laesst") (VGFC C2 . "liess") (PPRF . "gelassen")))
(l-s "laesst" '((STAMM "lass" . VGFB)))
(l-s "liess" '((STAMM "lass" . VGFC)))
(l-s "lauf" '(217000 (VGFB B1 . "laeuf") (VGFC C1 . "lief") (PPRF . "gelaufen")))
(l-s "laeuf" '((STAMM "lauf" . VGFB)))
(l-s "lief" '((STAMM "lauf" . VGFC)))
(l-s "rat" '(229100 (VGFB B3 . "raet") (VGFC C3 . "riet") (PPRF . "geraten")))
(l-s "raet" '((STAMM "rat" . VGFB)))
(l-s "riet" '((STAMM "rat" . VGFC)))
(l-s "schlaf" '(217100 (VGFB B1 . "schlaef") (VGFC C1 . "schlief") (PPRF . "geschlafen")))
(l-s "schlaef" '((STAMM "schlaf" . VGFB)))
(l-s "schlief" '((STAMM "schlaf" . VGFC)))
(l-s "stoss" '(253100 (VGFB B2 . "stoesst") (VGFC C2 . "stiess") (PPRF . "gestossen")))
(l-s "stoesst" '((STAMM "stoss" . VGFB)))
(l-s "stiess" '((STAMM "stoss" . VGFC)))

;; 6

(l-s "back" '(218100 (VGFB B1 . "baeck") (VGFC C1 . "buk") (VGFD . "bueke") (PPRF . "gebacken")))
(l-s "baeck" '((STAMM "back" . VGFB)))
(l-s "buk" '((STAMM "back" . VGFC)))
(l-s "bueke" '((STAMM "back" . VGFD)))
(l-s "back" '(213100 (PPRF . "gebacken")))
(l-s "fahr" '(218000 (VGFB B1 . "faehr") (VGFC C1 . "fuhr") (VGFD . "fuehre") (PPRF . "gefahren")))
(l-s "faehr" '((STAMM "fahr" . VGFB)))
(l-s "fuhr" '((STAMM "fahr" . VGFC)))
(l-s "fuehre" '((STAMM "fahr" . VGFD)))
(l-s "grab" '(218100 (VGFB B1 . "graeb") (VGFC C1 . "grub") (VGFD . "gruebe") (PPRF . "gegraben")))
(l-s "graeb" '((STAMM "grab" . VGFB)))
(l-s "grub" '((STAMM "grab" . VGFC)))
(l-s "gruebe" '((STAMM "grab" . VGFD)))

(l-s "lad" '(230100 (VGFB B1 . "laed") (VGFC C3 . "lud") (VGFD . "luede") (PPRF . "geladen")))
(l-s "laed" '((STAMM "lad" . VGFB)))
(l-s "lud" '((STAMM "lad" . VGFC)))
(l-s "luede" '((STAMM "lad" . VGFD)))
(l-s "sauf" '(218100 (VGFB B1 . "saeuf") (VGFC C1 . "soff") (VGFD . "soeffe") (PPRF . "gesoffen")))
(l-s "saeuf" '((STAMM "sauf" . VGFB)))
(l-s "soff" '((STAMM "sauf" . VGFC)))
(l-s "soeffe" '((STAMM "sauf" . VGFD)))
(l-s "schlag" '(218100 (VGFB B1 . "schlaeg") (VGFC C1 . "schlug") (VGFD . "schluege") (PPRF . "geschlagen")))
(l-s "schlaeg" '((STAMM "schlag" . VGFB)))
(l-s "schlug" '((STAMM "schlag" . VGFC)))
(l-s "schluege" '((STAMM "schlag" . VGFD)))
(l-s "trag" '(218100 (VGFB B1 . "traeg") (VGFC C1 . "trug") (VGFD . "truege") (PPRF . "getragen")))
(l-s "traeg" '((STAMM "trag" . VGFB)))
(l-s "trug" '((STAMM "trag" . VGFC)))
(l-s "truege" '((STAMM "trag" . VGFD)))
(l-s "wachs" '(254000 (VGFB B2 . "waechst") (VGFC C2 . "wuchs") (VGFD . "wuechse") (PPRF . "gewachsen")))
(l-s "waechst" '((STAMM "wachs" . VGFB)))
(l-s "wuchs" '((STAMM "wachs" . VGFC)))
(l-s "wuechse" '((STAMM "wachs" . VGFD)))
(l-s "wasch" '(254100 (VGFB B1 . "waesch") (VGFC C1 . "wusch") (VGFD . "wuesche") (PPRF . "gewaschen")))
(l-s "waesch" '((STAMM "wasch" . VGFB)))
(l-s "wusch" '((STAMM "wasch" . VGFC)))
(l-s "wuesche" '((STAMM "wasch" . VGFD)))

;; 7

(l-s "befehl" '(219100 (VGFB B1 . "befiehl") (VGFC C1 . "befahl") (VGFD . "befaehle") (PPRF . "befohlen")))
(l-s "befohl" '((STAMM "befehl" . PPRF)))
(l-s "befaehle" '((STAMM "befehl" . VGFD)))
(l-s "befahl" '((STAMM "befehl" . VGFC)))
(l-s "befiehl" '((STAMM "befehl" . VGFB)))
(l-s "berg" '(219100 (VGFB B1 . "birg") (VGFC C1 . "barg") (VGFD . "baerge") (PPRF . "geborgen")))
(l-s "borg" '((STAMM "berg" . PPRF)))
(l-s "baerge" '((STAMM "berg" . VGFD)))
(l-s "barg" '((STAMM "berg" . VGFC)))
(l-s "birg" '((STAMM "berg" . VGFB)))
(l-s "berst" '(231000 (VGFB B2 . "birst") (VGFC C3 . "barst") (VGFD . "baerste") (PPRF . "geborsten")))
(l-s "borst" '((STAMM "berst" . PPRF)))
(l-s "baerste" '((STAMM "berst" . VGFD)))
(l-s "barst" '((STAMM "berst" . VGFC)))
(l-s "birst" '((STAMM "berst" . VGFB)))
(l-s "brech" '(219100 (VGFB B1 . "brich") (VGFC C1 . "brach") (VGFD . "braeche") (PPRF . "gebrochen")))
(l-s "broch" '((STAMM "brech" . PPRF)))
(l-s "braeche" '((STAMM "brech" . VGFD)))
(l-s "brach" '((STAMM "brech" . VGFC)))
(l-s "brich" '((STAMM "brech" . VGFB)))
(l-s "dresch" '(219100 (VGFB B1 . "drisch") (VGFC C1 . "drosch") (VGFD . "droesche") (PPRF . "gedroschen")))
(l-s "droesche" '((STAMM "dresch" . VGFD)))
(l-s "drosch" '((STAMM "dresch" . VGFC)))
(l-s "drisch" '((STAMM "dresch" . VGFB)))
(l-s "empfehl" '(219100 (VGFB B1 . "empfiehl") (VGFC C1 . "empfahl") (VGFD . "empfaehle") (PPRF . "empfohlen")))
(l-s "empfohl" '((STAMM "empfehl" . PPRF)))
(l-s "empfaehle" '((STAMM "empfehl" . VGFD)))
(l-s "empfahl" '((STAMM "empfehl" . VGFC)))
(l-s "empfiehl" '((STAMM "empfehl" . VGFB)))
(l-s "ess" '(219100 (VGFB B4 . "iss") (VGFC C2 . "ass") (VGFD . "aesse") (PPRF . "gegessen")))
(l-s "gess" '((STAMM "ess" . PPRF)))
(l-s "aesse" '((STAMM "ess" . VGFD)))
(l-s "ass" '((STAMM "ess" . VGFC)))
(l-s "iss" '((STAMM "ess" . VGFB)))
(l-s "fecht" '(231100 (VGFB B3 . "ficht") (VGFC C3 . "focht") (VGFD . "foechte") (PPRF . "gefochten")))
(l-s "foechte" '((STAMM "fecht" . VGFD)))
(l-s "focht" '((STAMM "fecht" . VGFC)))
(l-s "ficht" '((STAMM "fecht" . VGFB)))
(l-s "flecht" '(231100 (VGFB B3 . "flicht") (VGFC C3 . "flocht") (VGFD . "floechte") (PPRF . "geflochten")))
(l-s "floechte" '((STAMM "flecht" . VGFD)))
(l-s "flocht" '((STAMM "flecht" . VGFC)))
(l-s "flicht" '((STAMM "flecht" . VGFB)))
(l-s "fress" '(255100 (VGFB B4 . "friss") (VGFC C2 . "frass") (VGFD . "fraesse") (PPRF . "gefressen")))
(l-s "fraesse" '((STAMM "fress" . VGFD)))
(l-s "frass" '((STAMM "fress" . VGFC)))
(l-s "friss" '((STAMM "fress" . VGFB)))
(l-s "geb" '(219100 (VGFB B1 . "gib") (VGFC C1 . "gab") (VGFD . "gaebe") (PPRF . "gegeben")))
(l-s "gaebe" '((STAMM "geb" . VGFD)))
(l-s "gab" '((STAMM "geb" . VGFC)))
(l-s "gib" '((STAMM "geb" . VGFB)))
(l-s "gebaer" '(219100 (VGFB B1 . "gebier") (VGFC C1 . "gebar") (VGFD . "gebaere") (PPRF . "geboren")))
(l-s "bor" '((STAMM "gebaer" . PPRF)))
(l-s "gebaere" '((STAMM "gebaer" . VGFD)))
(l-s "gebar" '((STAMM "gebaer" . VGFC)))
(l-s "gebier" '((STAMM "gebaer" . VGFB)))
(l-s "gelt" '(231100 (VGFB B3 . "gilt") (VGFC C3 . "galt") (VGFD . "gaelte") (PPRF . "gegolten")))
(l-s "golt" '((STAMM "gelt" . PPRF)))
(l-s "gaelte" '((STAMM "gelt" . VGFD)))
(l-s "galt" '((STAMM "gelt" . VGFC)))
(l-s "gilt" '((STAMM "gelt" . VGFB)))
(l-s "gescheh" '(219000 (VGFB B1 . "geschieh") (VGFC C1 . "geschah") (VGFD . "geschaehe") (PPRF . "geschehen")))
(l-s "geschaehe" '((STAMM "gescheh" . VGFD)))
(l-s "geschah" '((STAMM "gescheh" . VGFC)))
(l-s "geschieh" '((STAMM "gescheh" . VGFB)))
(l-s "helf" '(219100 (VGFB B1 . "hilf") (VGFC C1 . "half") (VGFD . "haelfe") (PPRF . "geholfen")))
(l-s "holf" '((STAMM "helf" . PPRF)))
(l-s "haelfe" '((STAMM "helf" . VGFD)))
(l-s "half" '((STAMM "helf" . VGFC)))
(l-s "hilf" '((STAMM "helf" . VGFB)))
(l-s "les" '(255100 (VGFB B4 . "lies") (VGFC C2 . "las") (VGFD . "laese") (PPRF . "gelesen")))
(l-s "laese" '((STAMM "les" . VGFD)))
(l-s "las" '((STAMM "les" . VGFC)))
(l-s "lies" '((STAMM "les" . VGFB)))
(l-s "melk" '(219100 (VGFB B1 . "milk") (VGFC C1 . "molk") (VGFD . "moelke") (PPRF . "gemolken")))
(l-s "moelke" '((STAMM "melk" . VGFD)))
(l-s "molk" '((STAMM "melk" . VGFC)))
(l-s "milk" '((STAMM "melk" . VGFB)))
(l-s "mess" '(255100 (VGFB B4 . "miss") (VGFC C2 . "mass") (VGFD . "maesse") (PPRF . "gemessen")))
(l-s "maesse" '((STAMM "mess" . VGFD)))
(l-s "mass" '((STAMM "mess" . VGFC)))
(l-s "miss" '((STAMM "mess" . VGFB)))
(l-s "nehm" '(219100 (VGFB B1 . "nimm") (VGFC C1 . "nahm") (VGFD . "naehme") (PPRF . "genommen")))
(l-s "nomm" '((STAMM "nehm" . PPRF)))
(l-s "naehme" '((STAMM "nehm" . VGFD)))
(l-s "nahm" '((STAMM "nehm" . VGFC)))
(l-s "nimm" '((STAMM "nehm" . VGFB)))
(l-s "quell" '(219000 (VGFB B1 . "quill") (VGFC C1 . "quoll") (VGFD . "quoelle") (PPRF . "gequollen")))
(l-s "quoelle" '((STAMM "quell" . VGFD)))
(l-s "quoll" '((STAMM "quell" . VGFC)))
(l-s "quill" '((STAMM "quell" . VGFB)))
(l-s "schelt" '(231100 (VGFB B3 . "schilt") (VGFC C3 . "schalt") (VGFD . "schoelte") (PPRF . "gescholten")))
(l-s "scholt" '((STAMM "schelt" . PPRF)))
(l-s "schoelte" '((STAMM "schelt" . VGFD)))
(l-s "schalt" '((STAMM "schelt" . VGFC)))
(l-s "schilt" '((STAMM "schelt" . VGFB)))
(l-s "schmelz" '(255000 (VGFB B4 . "schmilz") (VGFC C2 . "schmolz") (VGFD . "schmoelze") (PPRF . "geschmolzen")))
(l-s "schmoelze" '((STAMM "schmelz" . VGFD)))
(l-s "schmolz" '((STAMM "schmelz" . VGFC)))
(l-s "schmilz" '((STAMM "schmelz" . VGFB)))
(l-s "schreck" '(219000 (VGFB B1 . "schrick") (VGFC C1 . "schrak") (VGFD . "schraeke") (PPRF . "geschrocken")))
(l-s "schrock" '((STAMM "schreck" . PPRF)))
(l-s "schraeke" '((STAMM "schreck" . VGFD)))
(l-s "schrak" '((STAMM "schreck" . VGFC)))
(l-s "schrick" '((STAMM "schreck" . VGFB)))
(l-s "schwell" '(219000 (VGFB B1 . "schwill") (VGFC C1 . "schwoll") (VGFD . "schwoelle") (PPRF . "geschwollen")))
(l-s "schwoelle" '((STAMM "schwell" . VGFD)))
(l-s "schwoll" '((STAMM "schwell" . VGFC)))
(l-s "schwill" '((STAMM "schwell" . VGFB)))
(l-s "seh" '(219100 (VGFB B7 . "sieh") (VGFC C1 . "sah") (VGFD . "saehe") (PPRF . "gesehen")))
(l-s "saehe" '((STAMM "seh" . VGFD)))
(l-s "sah" '((STAMM "seh" . VGFC)))
(l-s "sieh" '((STAMM "seh" . VGFB)))
(l-s "sprech" '(219100 (VGFB B1 . "sprich") (VGFC C1 . "sprach") (VGFD . "spraeche") (PPRF . "gesprochen")))
(l-s "sproch" '((STAMM "sprech" . PPRF)))
(l-s "spraeche" '((STAMM "sprech" . VGFD)))
(l-s "sprach" '((STAMM "sprech" . VGFC)))
(l-s "sprich" '((STAMM "sprech" . VGFB)))
(l-s "stech" '(219100 (VGFB B1 . "stich") (VGFC C1 . "stach") (VGFD . "staeche") (PPRF . "gestochen")))
(l-s "stoch" '((STAMM "stech" . PPRF)))
(l-s "staeche" '((STAMM "stech" . VGFD)))
(l-s "stach" '((STAMM "stech" . VGFC)))
(l-s "stich" '((STAMM "stech" . VGFB)))
(l-s "stehl" '(219100 (VGFB B1 . "stiehl") (VGFC C1 . "stahl") (VGFD . "staehle") (PPRF . "gestohlen")))
(l-s "stohl" '((STAMM "stehl" . PPRF)))
(l-s "staehle" '((STAMM "stehl" . VGFD)))
(l-s "stahl" '((STAMM "stehl" . VGFC)))
(l-s "stiehl" '((STAMM "stehl" . VGFB)))
(l-s "sterb" '(219000 (VGFB B1 . "stirb") (VGFC C1 . "starb") (VGFD . "stuerbe") (PPRF . "gestorben")))
(l-s "storb" '((STAMM "sterb" . PPRF)))
(l-s "stuerbe" '((STAMM "sterb" . VGFD)))
(l-s "starb" '((STAMM "sterb" . VGFC)))
(l-s "stirb" '((STAMM "sterb" . VGFB)))
(l-s "treff" '(219100 (VGFB B1 . "triff") (VGFC C1 . "traf") (VGFD . "traefe") (PPRF . "getroffen")))
(l-s "troff" '((STAMM "treff" . PPRF)))
(l-s "traefe" '((STAMM "treff" . VGFD)))
(l-s "traf" '((STAMM "treff" . VGFC)))
(l-s "triff" '((STAMM "treff" . VGFB)))
(l-s "tret" '(231100 (VGFB B3 . "tritt") (VGFC C3 . "trat") (VGFD . "traete") (PPRF . "getreten")))
(l-s "traete" '((STAMM "tret" . VGFD)))
(l-s "trat" '((STAMM "tret" . VGFC)))
(l-s "tritt" '((STAMM "tret" . VGFB)))
(l-s "verderb" '(219100 (VGFB B1 . "verdirb") (VGFC C1 . "verdarb") (VGFD . "verduerbe") (PPRF . "verdorben")))
(l-s "verdorb" '((STAMM "verderb" . PPRF)))
(l-s "verduerbe" '((STAMM "verderb" . VGFD)))
(l-s "verdarb" '((STAMM "verderb" . VGFC)))
(l-s "verdirb" '((STAMM "verderb" . VGFB)))
(l-s "vergess" '(255100 (VGFB B4 . "vergiss") (VGFC C2 . "vergass") (VGFD . "vergaesse") (PPRF . "vergessen")))
(l-s "vergaesse" '((STAMM "vergess" . VGFD)))
(l-s "vergass" '((STAMM "vergess" . VGFC)))
(l-s "vergiss" '((STAMM "vergess" . VGFB)))
(l-s "werb" '(219100 (VGFB B1 . "wirb") (VGFC C1 . "warb") (VGFD . "wuerbe") (PPRF . "geworben")))
(l-s "worb" '((STAMM "werb" . PPRF)))
(l-s "wuerbe" '((STAMM "werb" . VGFD)))
(l-s "warb" '((STAMM "werb" . VGFC)))
(l-s "wirb" '((STAMM "werb" . VGFB)))
(l-s "werf" '(219100 (VGFB B1 . "wirf") (VGFC C1 . "warf") (VGFD . "wuerfe") (PPRF . "geworfen")))
(l-s "worf" '((STAMM "werf" . PPRF)))
(l-s "wuerfe" '((STAMM "werf" . VGFD)))
(l-s "warf" '((STAMM "werf" . VGFC)))
(l-s "wirf" '((STAMM "werf" . VGFB)))


(l-s "brauch" '((WORTART . verb) (VGFA . A1) (VTYP . 6) (VGFB B1 . "brauch") 
                (VGFC C4 . "brauchte") (VGFD . "braeuchte") 
                (PPRF . "brauchen") (PAUX . "hab")))
(l-s "brauch" '((STAMM "brauch" . VGFB)))
(l-s "brauchte" '((STAMM "brauch" . VGFC)))
(l-s "braeuchte" '((STAMM "brauch" . VGFD)))

