(in-package "MORPHIX")

(l-s "bescheidn" '((stamm "bescheiden" . elision)))
(l-s "dunkl" '((stamm "dunkel" . elision)))
(l-s "eign" '((stamm "eigen" . elision)))
(l-s "gross" '(330001 (sup . "groesst") (kom . "groesser")))
(l-s "groesst" '((stamm "gross" . sup)))
(l-s "groesser" '((stamm "gross" . kom)))
(l-s "heikl" '((stamm "heikel" . elision)))
(l-s "heitr" '((stamm "heiter" . elision)))
(l-s "komfortabl" '((stamm "komfortabel" . elision)))
(l-s "miserabl" '((stamm "miserabel" . elision)))
(l-s "teur" '((stamm "teuer" . elision)))
(l-s "variabl" '((stamm "variabel" . elision)))
(l-s "edl" '((stamm "edel" . elision)))
(l-s "besser" '((stamm "gut" . kom)))
(l-s "best" '((stamm "gut" . sup)))
(l-s "gut" '(330001 (kom . "besser") (sup . "best")))
(l-s "hoch" '(340001 (pos . "hoh") (kom . "hoeher") (sup . "hoechst")))
(l-s "hoh" '((stamm "hoch" . pos)))
(l-s "hoeher" '((stamm "hoch" . kom)))
(l-s "hoechst" '((stamm "hoch" . sup)))
(l-s "nah" '(330011 (kom . "naeher") (sup . "naechst")))
(l-s "naeher" '((stamm "nah" . kom)))
(l-s "naechst" '((stamm "nah" . sup)))
