;;; -*- Syntax: Common-lisp; Base: 10; Mode: LISP; Package: (:morphix :use :scl :colon-mode :external); Default-character-style: (:FIX :ROMAN :LARGE); -*-

(in-package :morphix)


(setq *IAL*
      '((root (nomen (red+ (uml+ (pl (1 8) (6 10))))
		     (red- (uml+ (sg (2 6) (3 6) (4 6) (5 6) (7 1) (1 8)
				     (8 1) (9 1) (6 5)))
			   (uml- (pl (1 8) (6 10))
				 (sg (2 6) (3 6) (4 6) (5 6) (7 1) (1 8)
				     (8 1) (9 1) (6 5)))))
	      (adjektiv (a1 (t ((red-uml+ red-uml- red-uml0)
				((t pos nec) ((st est irreg irreg-pos)
					      (t (pos 5))))))
			    (kom (red-uml-
				  (t ((irreg irreg-pos)
				      ((t pred-e) (kom 5))))))
			    (sup (red-uml-
				  (t ((irreg irreg-pos)
				      ((t pred-e) (sup 5)))))))
			(a2
			 (t (red-uml-
			     ((t pos nec) ((st est irreg irreg-pos nil)
				       (t (pos 5)))))))
			(a3 (t (red-uml- (t (nil (t (pos 5)))))))
                  			(c1 (t (red-uml- (t (nil (t (pos 5))))))))
	      ((possessivpronomen determinativ-indef)
	       ((1 2) ((sg+pl sg)
		       (artikelwort ((mas ((sg (nom))))
                                     (ntr ((sg (nom akk)))))))))
	      (verb (vtyp (1 (vgfa (a3 (praesens ((sg (1 3)))))
                                   ((a1 a5) (imperativ (sg))) ; a1 a5 neu 17/8/94
                                   ))
                          
			  (2 (vgfc (c4 (imperfekt ((sg (1 3)))))))
			  (3 (vgfc ((c1 c2 c3) (imperfekt ((sg (1 3)))))
				   (c4 (imperfekt ((sg (1 3))))
				       (konjunktiv-2 ((sg (1 3)))))))
			  (4 (vgfa ((a1 a7) (imperativ (sg)))) ; a1 neu 17/8/94
			     (vgfc ((c1 c2 c3 c4) (imperfekt ((sg (1 3))))))
			     (vgfd (konjunktiv-2 ((sg (1 3))))))
			  (5 (vgfb (b2 (praesens ((sg (2 3)))))
				   (b3 (praesens ((sg (3))))))
			     (vgfc ((c1 c2 c3) (imperfekt ((sg (1 3)))))))
			  (6 (vgfb (b2 (praesens ((sg (2 3)))))
                                   (b3 (praesens ((sg (3))))))
                             (vgfa (a1 (imperativ (sg)))) ; a1 neu 17/8/94
			     (vgfc ((c1 c2 c3 c4) (imperfekt ((sg (1 3))))))
			     (vgfd (konjunktiv-2 ((sg (1 3))))))
			  (7 (vgfb ((b1 b4 b7) (imperativ (sg)))
				   (b2 (praesens ((sg (2 3))))
				       (imperativ (sg)))
				   (b3 (praesens ((sg (3))))
				       (imperativ (sg))))
			     (vgfc ((c1 c2 c3) (imperfekt ((sg (1 3))))))
			     (vgfd (konjunktiv-2 ((sg (1 3))))))
			  (8 (vgfb (b3 (praesens ((sg (1 3)))))))
			  (9 (vgfb ((b3 b6) (praesens ((sg (1 3))))))
			     (vgfc (c4 (imperfekt ((sg (1 3)))))))
			  (10 (vgfb ((b3 b6) (praesens ((sg (1 3))))))
			      (vgfc (c4 (imperfekt ((sg (1 3))))))
			      (vgfd (konjunktiv-2 ((sg (1 3))))))
			  (11 (vgfc (c1 (imperfekt ((sg (1 3))))))
			      (sond1 (praesens ((sg (1)))))
			      (sond2 (praesens ((sg (2)))))
			      (sond3 (praesens ((sg (3)))))
			      (sond4 (praesens ((sg (anrede))
						(pl (1 3 anrede)))))
			      (vgfd (konjunktiv-2 ((sg (1 3)))))
			      (vgfa (a7 (konjunktiv-1 ((sg (1 3))))
					(imperativ (sg)))))))
	      (ordinalzahl ((ordinal no) 5)))
	(#\e (info "e")
	 (root (nomen (red+ (uml+ (pl (7 10))))
		      (red- (uml+ (sg (3 3) (4 3)))
			    (uml- (sg (3 3) (4 3))
				  (pl (7 10)))))
	       (adjektiv (a1 (t ((red-uml+ red-uml- red-uml0)
				 ((t pos) ((st est irreg)
					   (t (pos 0))
					   (pred-e (pos 0) (pos 5))))))
			     (elision (red-uml-
				       ((nec pos) ((st est)
						   ((t pred-e) (pos 0))))))
			     (pos (red-uml-
				   (t (irreg-pos (t (pos 0))
						 (pred-e (pos 0) (pos 5))))))
			     (kom (red-uml-
				   (t ((irreg irreg-pos)
				       ((t pred-e) (kom 0))))))
			     (sup (red-uml-
				   (t ((irreg irreg-pos)
				       ((t pred-e) (sup 0)))))))
			 (b1 (t ((red-uml+ red-uml- red-uml0)
				 ((t pos) ((st est) ((t pred-e) (pos 0))))))
			     (elision (red-uml-
				       ((nec pos) ((st est)
						   ((t pred-e) (pos 0)))))))
			 ((a2 b2)
			  (t (red-uml-
			      ((t pos) ((st est irreg nil)
					(t (pos 0))
					(pred-e (pos 0) (pos 5))))))
			  (elision (red-uml-
				    ((nec pos) ((st est nil)
						((t pred-e) (pos 0))))))
			  (pos (red-uml-
				(t (irreg-pos (t (pos 0))
					      (pred-e (pos 0) (pos 5)))))))
			 (c1 (t (red-uml- (t (nil (pred-e (pos 5))))))))
	       ((possessivpronomen determinativ determinativ-indef)
		((1 2 3)
		 (sg+pl
		  (substantivwort
		   ((ohne ((mas ((pl (nom akk))))
			   (fem ((sg (nom akk)) (pl (nom akk))))
			   (ntr ((pl (nom akk))))))
		    (bestimmt ((mas ((sg (nom))))
			       (fem ((sg (nom akk))))
			       (ntr ((sg (nom akk))))))))
		  (artikelwort ((mas ((pl (nom akk))))
				(fem ((sg (nom akk)) (pl (nom akk))))
				(ntr ((pl (nom akk)))))))
		 (sg (artikelwort ((fem ((sg (nom akk)))))))
		 (pl (artikelwort ((mas ((pl (nom akk))))
				   (fem ((pl (nom akk))))
				   (ntr ((pl (nom akk)))))))))
	       (verb (vtyp (1 (vgfa ((a1 a2 a4 a6)
				     (praesens ((sg (1))))
				     (konjunktiv-1 ((sg (1 3))))
				     (imperativ (sg)))
				    (a3 (konjunktiv-1 ((sg (1 3))))))
			      (vgfa+ ((a5 a6) (praesens ((sg (1))))
				      (konjunktiv-1 ((sg (1 3))))
				      (imperativ (sg)))))
			   (2 (vgfa ((a1 a2) (praesens ((sg (1))))
				     (konjunktiv-1 ((sg (1 3))))
				     (imperativ (sg)))))
			   (3 (vgfa ((a1 a2 a4)
				     (praesens ((sg (1))))
				     (konjunktiv-1 ((sg (1 3))))
				     (imperativ (sg))))
			      (vgfc ((c1 c2 c3)
				     (konjunktiv-2 ((sg (1 3)))))))
			   (4 (vgfa ((a1 a2 a4)
				     (praesens ((sg (1))))
				     (konjunktiv-1 ((sg (1 3))))
				     (imperativ (sg))) 
				    (a7 (praesens ((sg (1))))
					(konjunktiv-1 ((sg (1 3)))))))
			   (5 (vgfa ((a1 a2 a4)
				     (praesens ((sg (1))))
				     (konjunktiv-1 ((sg (1 3))))
				     (imperativ (sg))))
			      (vgfc ((c1 c2 c3) (konjunktiv-2 ((sg (1 3)))))))
			   (6 (vgfa ((a1 a2 a4)
				     (praesens ((sg (1))))
				     (konjunktiv-1 ((sg (1 3))))
				     (imperativ (sg)))))
			   (7 (vgfa ((a1 a2 a4)
				     (praesens ((sg (1))))
				     (konjunktiv-1 ((sg (1 3))))))
			      (vgfb (b7 (imperativ (sg)))))
			   (8 (vgfa (a1 (konjunktiv-1 ((sg (1 3))))
					(imperativ (sg)))))
			   (9 (vgfa ((a1 a4)
				     (konjunktiv-1 ((sg (1 3))))
				     (imperativ (sg)))))
			   (10 (vgfa ((a1 a4)
				      (konjunktiv-1 ((sg (1 3)))))))))
	       (ordinalzahl ((ordinal no ordinal-b) 0)))
	 (#\d
	  (#\n (info "nde" "e")
	   (root (verb (weg "nd" "e")))
	   (#\e (info "ende" "e")
	    (root (verb (weg "end" "e"))))))
	 (#\r
	  (#\e (info "ere" "e")
	   (root (adjektiv (a1 (t ((red+uml+ red-uml- red+uml0 red-uml0)
				   ((t pos) ((st est)
					     ((t pred-e) (kom 0))))))
			       (elision (red-uml-
					 ((nec pos) ((st est)
						     ((t pred-e) 
						      (kom 0)))))))))
	   (#\d
	    (#\n (info "ndere" "ere" "e")
	     (root (verb (weg "nd" "ere")))
	     (#\e (info "endere" "ere" "e")
	      (root (verb (weg "end" "ere"))))))
	   (#\t (info "tere" "ere" "e")
	    (root (verb (weg "t" "ere")))
	    (#\e (info "etere" "tere" "ere" "e")
	     (root (verb (weg "et" "ere")))))
	   (#\n
	    (#\e (info "enere" "ere" "e")
	     (root (verb (weg "en" "ere")))))))
	 (#\s (info "se" "e")
	  (root (nomen (red+ (uml+ (pl (8 10))))
		       (red- (uml- (sg (5 3)) (pl (8 10)))
			     (uml+ (sg (5 3)))))))
	 (#\t (info "te" "e")
	  (root (nomen (red+ (uml+ (pl (13 10))))
		       (red- (uml- (pl (13 10)))))
		(verb (weg "t" "e")
		      (vtyp (1 (vgfa ((a1 a3 a4 a5 a6)
				      (imperfekt ((sg (1 3))))
				      (konjunktiv-2 ((sg (1 3)))))))
			    (2 (vgfa (a1 (konjunktiv-2 ((sg (1 3)))))))
			    (8 (vgfa (a1 (imperfekt ((sg (1 3))))
					 (konjunktiv-2 ((sg (1 3)))))))
			    (9 (vgfa ((a1 a4) 
				      (konjunktiv-2 ((sg (1 3)))))))))
		(ordinalzahl (t 0)))
	  (#\s (info "ste" "te" "e")
	   (root (adjektiv ((a1 b1)
			    (t ((red+uml+ red-uml- red+uml0 red-uml0)
				((t nec pos)
				 (st ((t pred-e) (sup 0))))))))
		 (ordinalzahl (st 0)))
	   (#\d
	    (#\n (info "ndste" "ste" "e")
	     (root (verb (weg "nd" "ste")))
	     (#\e (info "endste" "ste" "e")
	      (root (verb (weg "end" "ste"))))))
	   (#\t (info "tste" "ste" "e")
	    (root (verb (weg "t" "ste")))
	    (#\e (info "etste" "tste" "ste" "e")
	     (root (verb (weg "et" "ste")))))
	   (#\n
	    (#\e (info "enste" "ste" "e")
	     (root (verb (weg "en" "ste")))))
	   (#\e (info "este" "ste" "te" "e") ; hierix
	    (root (adjektiv ((a1 b1)
			     (t ((red+uml+ red-uml-
					   red+uml0 red-uml0)
				 ((t nec pos)
				  (est
				   ((t pred-e)
				    (sup 0)))))))))
	    (#\t (info "teste" "este" "e")
	     (root (verb (weg "t" "este"))))))
	  (#\e (info "ete" "te" "e")
	   (root (verb (weg "et" "e")
		       (vtyp ((1 2)
			      (vgfa (a2 (imperfekt ((sg (1 3))))
					(konjunktiv-2 ((sg (1 3))))))))))))
	 (#\n (info "ne" "e")
	  (root (verb (weg "n" "e")))
	  (#\e (info "ene" "e")
	   (root (verb (weg "en" "e")))))
	 
	 )
	(#\n (info "n")
	 (root
	   (nomen (red+ (uml+ (pl (3 8) (6 3))))
		  (red- (uml- (sg (8 7) (7 4)) (pl (3 8) (6 3)))
			(uml+ (sg (8 7) (7 4)))))
	   (verb (partizip pprf)
		 (vtyp (1 (vgfa
			    ((a5 a6)
			     (praesens ((sg (anrede)) (pl (1 3 anrede))))
			     (konjunktiv-1 ((sg (anrede)) (pl (1 3 anrede))))
			     (infinitiv)
			     (imperativ (anrede)))))
		       ((2 9) (vgfc (c4 (imperfekt
					  ((sg (anrede))
					   (pl (1 3 anrede)))))))
		       (3 (vgfc (c4 (imperfekt
				      ((sg (anrede)) (pl (1 3 anrede))))
				    (konjunktiv-2
				      ((sg (anrede)) (pl (1 3 anrede)))))))
		       (4 (vgfa (a7 (praesens
				      ((sg (anrede)) (pl (1 3 anrede))))
				    (konjunktiv-1
				      ((sg (anrede)) (pl (1 3 anrede))))
				    (infinitiv)
				    (imperativ (anrede))))
			  (vgfc (c4 (imperfekt
				      ((sg (anrede)) (pl (1 3 anrede))))))
			  (vgfd (konjunktiv-2
				  ((sg (anrede)) (pl (1 3 anrede))))))
		       ((6 10)
			(vgfc (c4 (imperfekt
				    ((sg (anrede)) (pl (1 3 anrede))))))
			(vgfd (konjunktiv-2
				((sg (anrede)) (pl (1 3 anrede))))))
		       (7 (vgfd (konjunktiv-2
				  ((sg (anrede)) (pl (1 3 anrede))))))
		       (11 (vgfa (a7 (infinitiv)))
			   (vgfd (konjunktiv-2
				   ((sg (anrede)) (pl (1 3 anrede))))))))
	   (possessivpronomen
	     (2 (sg+pl
		  (substantivwort
		    ((ohne ((mas ((sg (akk)) (pl (dat))))
			    (fem ((pl (dat))))
			    (ntr ((pl (dat))))))
		     (bestimmt ((mas ((sg (gen dat akk))
				      (pl (nom gen dat akk))))
				(fem ((sg (gen dat))
				      (pl (nom gen dat akk))))
				(ntr ((sg (gen dat))
				      (pl (nom gen dat akk))))))))
		  (artikelwort ((mas ((sg (akk)) (pl (dat))))
				(fem ((pl (dat))))
				(ntr ((pl (dat))))))))))
	 (#\e (info "en" "n")
	  (root (nomen (red+ (uml+ (pl (4 8) (7 3))))
		       (red- (uml- (sg (9 7) (6 3)) (pl (4 8) (7 3)))
			     (uml+ (sg (9 7) (6 3)))))
		(adjektiv (a1 (t ((red-uml+ red-uml- red-uml0)
				  ((t pos) ((st est irreg)
					    ((t pred-e) (pos 1))))))
			      (elision (red-uml-
					 ((nec pos) ((st est)
						     ((t pred-e) (pos 1))))))
			      (pos (red-uml-
				     (t (irreg-pos ((t pred-e) (pos 1))))))
			      (kom (red-uml-
				     (t ((irreg irreg-pos)
					 ((t pred-e) (kom 1))))))
			      (sup (red-uml-
				     (t ((irreg irreg-pos)
					 ((t pred-e) (sup 1)))))))
			  (b1 (t ((red-uml+ red-uml- red-uml0)
				  ((t pos) ((st est)
					    ((t pred-e) (pos 1))))))
			      (elision (red-uml-
					 ((nec pos)
					  ((st est)
					   ((t pred-e) (pos 1)))))))
			  ((a2 b2)
			   (t (red-uml-
				((t pos) ((st est irreg nil)
					  ((t pred-e) (pos 1))))))
			   (elision (red-uml-
				      ((nec pos) ((st est nil) ((t pred-e) (pos 1))))))
			   (pos (red-uml-
				  (t (irreg-pos ((t pred-e) (pos 1))))))))
		(verb (partizip pprf)
		      (vtyp (1 (vgfa ((a1 a2 a3 a4)
				      (praesens ((sg (anrede))
						 (pl (1 3 anrede))))
				      (konjunktiv-1 ((sg (anrede))
						     (pl (1 3 anrede))))
				      (infinitiv)
				      (imperativ (anrede)))))
			    (2 (vgfa ((a1 a2)
				      (praesens ((sg (anrede))
						 (pl (1 3 anrede))))
				      (konjunktiv-1 ((sg (anrede))
						     (pl (1 3 anrede))))
				      (infinitiv)
				      (imperativ (anrede)))))
			    ((3 5) (vgfa ((a1 a2 a4)
					  (praesens ((sg (anrede))
						     (pl (1 3 anrede))))
					  (konjunktiv-1 ((sg (anrede))
							 (pl (1 3 anrede))))
					  (infinitiv)
					  (imperativ (anrede))))
			     (vgfc ((c1 c2 c3)
				    (imperfekt ((sg (anrede))
						(pl (1 3 anrede))))
				    (konjunktiv-2 ((sg (anrede))
						   (pl (1 3 anrede)))))))
			    ((4 7) (vgfa ((a1 a2 a4)
					  (praesens ((sg (anrede))
						     (pl (1 3 anrede))))
					  (konjunktiv-1 ((sg (anrede))
							 (pl (1 3 anrede))))
					  (infinitiv)
					  (imperativ (anrede))))
			     (vgfc ((c1 c2 c3)
				    (imperfekt ((sg (anrede))
						(pl (1 3 anrede)))))))
			    (6 (vgfa ((a1 a2 a4)
				      (praesens ((sg (anrede))
						 (pl (1 3 anrede))))
				      (konjunktiv-1 ((sg (anrede))
						     (pl (1 3 anrede))))
				      (infinitiv)
				      (imperativ (anrede))))
			       (vgfc ((c1 c2 c3)
				      (imperfekt ((sg (anrede))
						  (pl (1 3 anrede)))))))
			    (8 (vgfa (a1 (praesens ((sg (anrede))
						    (pl (1 3 anrede))))
					 (konjunktiv-1 ((sg (anrede))
							(pl (1 3 anrede))))
					 (infinitiv)
					 (imperativ (anrede)))))
			    ((9 10) (vgfa ((a1 a4)
					   (praesens ((sg (anrede))
						      (pl (1 3 anrede))))
					   (konjunktiv-1 ((sg (anrede))
							  (pl (1 3 anrede))))
					   (infinitiv)
					   (imperativ (anrede)))))
			    (11 (vgfa (a7 (konjunktiv-1 ((sg (anrede))
							 (pl (1 3 anrede))))
					  (imperativ (anrede))))
				(vgfc (c1 (imperfekt
					    ((sg (anrede))
					     (pl (1 3 anrede)))))))))
		((possessivpronomen determinativ determinativ-indef)
		 ((1 2 3)
		  (sg+pl
		    (substantivwort
		      ((ohne ((mas ((sg (akk)) (pl (dat))))
			      (fem ((pl (dat))))
			      (ntr ((pl (dat))))))
		       (bestimmt ((mas ((sg (gen dat akk))
					(pl (nom gen dat akk))))
				  (fem ((sg (gen dat))
					(pl (nom gen dat akk))))
				  (ntr ((sg (gen dat))
					(pl (nom gen dat akk))))))))
		    (artikelwort ((mas ((sg (akk)) (pl (dat))))
				  (fem ((pl (dat))))
				  (ntr ((pl (dat)))))))
		  (sg (artikelwort ((mas ((sg (akk)))))))
		  (pl (artikelwort ((mas ((pl (dat))))
				    (fem ((pl (dat))))
				    (ntr ((pl (dat)))))))))
		(ordinalzahl ((ordinal no ordinal-b) 1)))
	  (#\d
	   (#\n (info "nden" "en" "n")
	    (root (verb (weg "nd" "en")))
	    (#\e (info "enden" "en" "n")
	     (root (verb (weg "end" "en"))))))
	  (#\r
	   (#\e (info "eren" "en" "n")
	    (root (adjektiv (a1 (t ((red+uml+ red-uml- red+uml0 red-uml0)
				    ((t pos) ((st est)
					      ((t pred-e) (kom 1))))))
				(elision (red-uml-
					   ((nec pos)
					    ((st est)
					     ((t pred-e) (kom 1)))))))))
	    (#\d
	     (#\n (info "nderen" "eren" "en" "n")
	      (root (verb (weg "nd" "eren")))
	      (#\e (info "enderen" "eren" "en" "n")
	       (root (verb (weg "end" "eren"))))))
	    (#\t (info "teren" "eren" "en" "n")
	     (root (verb (weg "t" "eren")))
	     (#\e (info "eteren" "teren" "eren" "en" "n")
	      (root (verb (weg "et" "eren")))))
	    (#\n
	     (#\e (info "eneren" "eren" "en" "n")
	      (root (verb (weg "en" "eren")))))))
	  (#\s (info "sen" "en" "n")
	   (root (nomen (red+ (uml+ (pl (8 3) (11 8))))
			(red- (uml- (pl (8 3) (11 8)))))))
	  (#\t (info "ten" "en" "n")
	   (root (nomen (red+ (uml+ (pl (12 8) (13 3))))
			(red- (uml- (pl (12 8) (13 3)))))
		 (verb (weg "t" "en")
		       (vtyp (1 (vgfa ((a1 a3 a4 a5 a6)
				       (imperfekt ((sg (anrede)) (pl (1 3 anrede))))
				       (konjunktiv-2 ((sg (anrede)) (pl (1 3 anrede)))))))
			     (2 (vgfa (a1 (konjunktiv-2 ((sg (anrede)) (pl (1 3 anrede)))))))
			     (8 (vgfa (a1 (imperfekt ((sg (anrede)) (pl (1 3 anrede))))
					  (konjunktiv-2 ((sg (anrede)) (pl (1 3 anrede)))))))
			     (9 (vgfa ((a1 a4) (konjunktiv-2 ((sg (anrede)) (pl (1 3 anrede)))))))))
		 (ordinalzahl (t 1)))
	   (#\s (info "sten" "ten" "en" "n")
	    (root (adjektiv ((a1 b1) (t ((red+uml+ red-uml- red+uml0 red-uml0)
					 ((t nec pos) (st ((t pred-e) (sup 1))))))))
		  (ordinalzahl (st 1)))
	    (#\d
	     (#\n (info "ndsten" "sten" "en" "n")
	      (root (verb (weg "nd" "sten")))
	      (#\e (info "endsten" "ndsten" "sten" "en" "n")
	       (root (verb (weg "end" "sten"))))))
	    (#\t (info "tsten" "sten" "en" "n")
	     (root (verb (weg "t" "sten")))
	     (#\e (info "etsten" "tsten" "sten" "en" "n")
	      (root (verb (weg "et" "sten")))))
	    (#\n
	     (#\e (info "ensten" "sten" "en" "n")
	      (root (verb (weg "en" "sten")))))
	    (#\e (info "esten" "sten" "ten" "en" "n")
	     (root (adjektiv ((a1 b1) (t ((red+uml+ red-uml- red+uml0 red-uml0)
					  ((t nec pos) (est ((t pred-e) (sup 1)))))))))
	     (#\t (info "testen" "esten" "en" "n")
	      (root (verb (weg "t" "esten"))))))
	   (#\e (info "eten" "ten" "en" "n")
	    (root (verb (weg "et" "en")
			(vtyp ((1 2) (vgfa (a2 (imperfekt ((sg (anrede)) (pl (1 3 anrede))))
					       (konjunktiv-2 ((sg (anrede)) (pl (1 3 anrede))))))))))))
	  (#\n (info "nen" "en" "n")
	   (root (nomen (red+ (uml+ (pl (5 8))))
			(red- (uml- (pl (5 8)))))
		 (verb (weg "n" "en")))
	   (#\e (info "enen" "nen" "en" "n")
	    (root (verb (weg "en" "en")))))
	  (#\i (info "ien" "en" "n")
	   (root (nomen (red+ (uml+ (pl (10 8))))
			(red- (uml- (pl (10 8))))))))
	 (#\r
	  (#\e (info "ern" "n")
	   (root (nomen (red+ (uml+ (pl (9 3))))
			(red- (uml- (pl (9 3))))))))
	 
	 )
	(#\s (info "s")
	 (root (nomen (red+ (uml+ (pl (2 8))))
		      (red- (uml- (sg (2 2) (4 2)) (pl (2 8)))
			    (uml+ (sg (2 2) (4 2)))))
	       (possessivpronomen
		((1 2)
		 (sg+pl
		  (substantivwort ((ohne ((ntr ((sg (nom akk))))))))
		  (artikelwort ((mas ((sg (gen)))) (ntr ((sg (gen))))))))))
	 (#\e (info "es" "s")
	  (root (nomen (red- (uml- (sg (3 2) (4 2)))
			     (uml+ (sg (3 2) (4 2)))))
		(adjektiv (a1 (t ((red-uml+ red-uml- red-uml0)
				  ((t pos) ((st est irreg) ((t pred-e) (pos 2))))))
			      (elision (red-uml-
					((nec pos) ((st est) ((t pred-e) (pos 2))))))
			      (pos (red-uml-
				    (t (irreg-pos ((t pred-e) (pos 2))))))
			      (kom (red-uml-
				    (t ((irreg irreg-pos) ((t pred-e) (kom 2))))))
			      (sup (red-uml-
				    (t ((irreg irreg-pos) ((t pred-e) (sup 2)))))))
			  (b1 (t ((red-uml+ red-uml- red-uml0)
				  ((t pos) ((st est) ((t pred-e) (pos 2))))))
			      (elision (red-uml-
					((nec pos) ((st est) ((t pred-e) (pos 2)))))))
			  ((a2 b2)
			   (t (red-uml-
			       ((t pos) ((st est irreg nil) ((t pred-e) (pos 2))))))
			   (elision (red-uml-
				     ((nec pos) ((st est nil) ((t pred-e) (pos 2))))))
			   (pos (red-uml-
				 (t (irreg-pos ((t pred-e) (pos 2))))))))
		((possessivpronomen determinativ-indef)
		 ((1 2 3)
		  ((sg+pl sg)
		   (artikelwort ((mas ((sg (gen))))
				 (ntr ((sg (gen))))))
		   (substantivwort ((ohne ((ntr ((sg (nom gen akk)))))))))))
		(determinativ
		 (1 ((sg+pl sg)
		     (artikelwort ((mas ((sg (gen))))
				   (ntr ((sg (nom akk gen)))))))))
		(ordinalzahl ((ordinal ordinal-b no) 2)))

	  (#\d
	   (#\n (info "ndes" "es" "s")
	    (root (verb (weg "nd" "es")))
	    (#\e (info "endes" "es" "s")
	     (root (verb (weg "end" "es"))))))
	  (#\r
	   (#\e (info "eres" "es" "s")
	    (root (adjektiv (a1 (t ((red+uml+ red-uml- red+uml0 red-uml0)
				    ((t pos) ((st est) ((t pred-e) (kom 2))))))
				(elision (red-uml-
					  ((nec pos) ((st est) ((t pred-e) (kom 2)))))))))
	    (#\d
	     (#\n (info "nderes" "eres" "es" "s")
	      (root (verb (weg "nd" "eres")))
	      (#\e (info "enderes" "eres" "es" "s")
	       (root (verb (weg "end" "eres"))))))
	    (#\t (info "teres" "eres" "es" "s")
	     (root (verb (weg "t" "eres")))
	     (#\e (info "eteres" "teres" "eres" "es" "s")
	      (root (verb (weg "et" "eres")))))
	    (#\n
	     (#\e (info "eneres" "eres" "es" "s")
	      (root (verb (weg "en" "eres")))))))
	  (#\s (info "ses" "es" "s")
	   (root (nomen (red- (uml- (sg (5 2)))
			      (uml+ (sg (5 2)))))))
	  (#\t (info "tes" "es" "s")
	   (root (verb (weg "t" "es"))
		 (ordinalzahl (t 2)))
	   (#\s (info "stes" "tes" "es" "s") ; hierix
	    (root (adjektiv ((a1 b1) (t ((red+uml+ red-uml- red+uml0 red-uml0)
					 ((t nec pos) (st ((t pred-e) (sup 2))))))))
		  (ordinalzahl (st 2)))
	    (#\d
	     (#\n (info "ndstes" "stes" "es" "s")
	      (root (verb (weg "nd" "stes")))
	      (#\e (info "endstes" "stes" "es" "s")
	       (root (verb (weg "end" "stes"))))))
	    (#\t (info "tstes" "stes" "es" "s")
	     (root (verb (weg "t" "stes")))
	     (#\e (info "etstes" "tstes" "stes" "es" "s")
	      (root (verb (weg "et" "stes")))))
	    (#\n
	     (#\e (info "enstes" "stes" "es" "s")
	      (root (verb (weg "en" "stes")))))
	    (#\e (info "estes" "stes" "tes" "es" "s") ; hierix
	     (root (adjektiv ((a1 b1) (t ((red+uml+ red-uml- red+uml0 red-uml0)
					  ((t nec pos) (est ((t pred-e) (sup 2)))))))))
	     (#\t (info "testes" "estes" "es" "s")
	      (root (verb (weg "t" "estes"))))))
	   (#\e (info "etes" "tes" "es" "s")
	    (root (verb (weg "et" "es")))))
	  (#\n (info "nes" "es" "s")
	   (root (verb (weg "n" "es")))
	   (#\e (info "enes" "es" "s")
	    (root (verb (weg "en" "es"))))))
	 (#\n (info "ns" "s")
	  (root (nomen (red- (uml- (sg (7 2)))
			     (uml+ (sg (7 2))))))
	  (#\e (info "ens" "ns" "s")
	   (root (nomen (red- (uml- (sg (6 2)))
			      (uml+ (sg (6 2))))))))
	 
	 )
	(#\r
	 (#\e (info "er")
	  (root (nomen (red+ (uml+ (pl (9 10))))
		       (red- (uml- (pl (9 10)))))
		(adjektiv (a1 (t ((red+uml+ red+uml0)
				  ((t pos) ((st est) ((t pred-e) (kom 5)))))
				 ((red-uml- red-uml0)
				  ((t pos)
				   ((st est) ((t pred-e) (pos 4) (kom 5)))
				   (irreg ((t pred-e) (pos 4)))))
				 (red-uml+
				  ((t pos) ((st est) ((t pred-e) (pos 4))))))
			      (elision (red-uml-
					((nec pos) ((st est) ((t pred-e) (pos 4) (kom 5))))))
			      (pos (red-uml-
				    (t (irreg-pos ((t pred-e) (pos 4))))))
			      (kom (red-uml-
				    (t ((irreg irreg-pos) ((t pred-e) (kom 4))))))
			      (sup (red-uml-
				    (t ((irreg irreg-pos) ((t pred-e) (sup 4)))))))
			  (b1 (t ((red-uml+ red-uml- red-uml0)
				  ((t pos) ((st est) ((t pred-e) (pos 4))))))
			      (elision (red-uml-
					((nec pos) ((st est) ((t pred-e) (pos 4)))))))
			  ((a2 b2)
			   (t (red-uml-
			       ((t pos) ((st est irreg nil) ((t pred-e) (pos 4))))))
			   (elision (red-uml-
				     ((nec pos) ((st est nil) ((t pred-e) (pos 4))))))
			   (pos (red-uml-
				 (t (irreg-pos ((t pred-e) (pos 4))))))))
		(determinativ
		 (1 (sg+pl
		     (artikelwort
		      ((mas ((sg (nom)) (pl (gen))))
		       (fem ((sg (gen dat)) (pl (gen))))
		       (ntr ((pl (gen)))))))
		    (sg
		     (artikelwort ((mas ((sg (nom))))
				   (fem ((sg (gen dat)))))))
		    (pl (artikelwort ((mas ((pl (gen))))
				      (fem ((pl (gen))))
				      (ntr ((pl (gen)))))))))
		((possessivpronomen determinativ-indef)
		 ((1 2 3)
		  (sg+pl
		   (substantivwort
		    ((ohne ((mas ((sg (nom)) (pl (gen))))
			    (fem ((sg (gen dat)) (pl (gen))))
			    (ntr ((pl (gen))))))))
		   (artikelwort ((mas ((pl (gen))))
				 (fem ((sg (gen dat)) (pl (gen))))
				 (ntr ((pl (gen)))))))
		  (sg (artikelwort ((fem ((sg (gen dat)))))))
		  (pl (artikelwort ((mas ((pl (gen))))
				    (fem ((pl (gen))))
				    (ntr ((pl (gen)))))))))
		(ordinalzahl ((ordinal no ordinal-b) 4)))
	  (#\d
	   (#\n (info "nder" "er")
	    (root (verb (weg "nd" "er")))
	    (#\e (info "ender" "er")
	     (root (verb (weg "end" "er"))))))
	  (#\r
	   (#\e (info "erer" "er")
	    (root (adjektiv (a1 (t ((red+uml+ red-uml- red+uml0 red-uml0)
				    ((t pos) ((st est) ((t pred-e) (kom 4))))))
				(elision (red-uml-
					  ((nec pos) ((st est) ((t pred-e) (kom 4)))))))))
	    (#\d
	     (#\n (info "nderer" "erer" "er")
	      (root (verb (weg "nd" "erer")))
	      (#\e (info "enderer" "erer" "er")
	       (root (verb (weg "end" "erer"))))))
	    (#\t (info "terer" "erer" "er")
	     (root (verb (weg "t" "erer")))
	     (#\e (info "eterer" "terer" "erer" "er")
	      (root (verb (weg "et" "erer")))))
	    (#\n
	     (#\e (info "enerer" "erer" "er")
	      (root (verb (weg "en" "erer")))))))
	  (#\t (info "ter" "er")
	   (root (verb (weg "t" "er"))
		 (ordinalzahl (t 4)))
	   (#\s (info "ster" "ter" "er") ; hierix
	    (root (adjektiv ((a1 b1) (t ((red+uml+ red-uml- red+uml0 red-uml0)
					 ((t nec pos) (st ((t pred-e) (sup 4))))))))
		  (ordinalzahl (st 4)))
	    (#\d
	     (#\n (info "ndster" "ster" "er")
	      (root (verb (weg "nd" "ster")))
	      (#\e (info "endster" "ster" "er")
	       (root (verb (weg "end" "ster"))))))
	    (#\t (info "tster" "ster" "er")
	     (root (verb (weg "t" "ster")))
	     (#\e (info "etster" "tster" "ster" "er")
	      (root (verb (weg "et" "ster")))))
	    (#\n
	     (#\e (info "enster" "ster" "er")
	      (root (verb (weg "en" "ster")))))
	    (#\e (info "ester" "ster" "ter" "er") ; hierix
	     (root (adjektiv ((a1 b1) (t ((red+uml+ red-uml- red+uml0 red-uml0)
					  ((t nec pos) (est ((t pred-e) (sup 4)))))))))
	     (#\t (info "tester" "ster" "er")
	      (root (verb (weg "t" "ester"))))))
	   (#\e (info "eter" "ter" "er")
	    (root (verb (weg "et" "er")))))
	  (#\n (info "ner" "er")
	   (root (verb (weg "n" "er")))
	   (#\e (info "ener" "er")
	    (root (verb (weg "en" "er"))))))
     
	 )
	(#\t (info "t")
	 (root (verb (partizip pprf)
		     (vtyp (1 (vgfa (a1 (praesens ((sg (3)) (pl (2))))
					(imperativ (pl)))
				    (a3 (praesens ((pl (2))))
					(imperativ (pl)))
				    (a4 (praesens ((sg (2 3)) (pl (2))))
					(imperativ (pl)))
				    (a5 (praesens ((sg (3)) (pl (2))))
					(konjunktiv-1 ((sg (3)) (pl (2))))
					(imperativ (pl)))
				    (a6 (praesens ((sg (3)) (pl (2))))
					(konjunktiv-1 ((sg (3)) (pl (2))))
					(imperativ (pl)))))
			   (2 (vgfa (a1 (praesens ((sg (3)) (pl (2))))
					(imperativ (pl))))
			      (vgfc (c4 (imperfekt ((pl (2)))))))
			   (3 (vgfa (a1 (praesens ((sg (3)) (pl (2))))
					(imperativ (pl)))
				    (a4 (praesens ((sg (2 3)) (pl (2))))
					(imperativ (pl))))
			      (vgfc ((c1 c2) (imperfekt ((pl (2)))))
				    (c4 (imperfekt ((pl (2))))
					(konjunktiv-2 ((pl (2)))))))
			   (4 (vgfa (a1 (praesens ((sg (3)) (pl (2))))
					(imperativ (pl)))
				    (a4 (praesens ((sg (2 3)) (pl (2))))
					(imperativ (pl)))
				    (a7 (praesens ((sg (3)) (pl (2))))
					(konjunktiv-1 ((pl (2))))
					(imperativ (pl))))
			      (vgfc ((c1 c2 c4) (imperfekt ((pl (2))))))
			      (vgfd (konjunktiv-2 ((pl (2))))))
			   (5 (vgfa ((a1 a4)
				     (praesens ((pl (2))))
				     (imperativ (pl))))
			      (vgfb (b1 (praesens ((sg (3)))))
				    (b4 (praesens ((sg (2 3))))))
			      (vgfc ((c1 c2) (imperfekt ((pl (2)))))))
			   (6 (vgfa ((a1 a4) (praesens ((pl (2))))
					(imperativ (pl))))
			      (vgfb (b1 (praesens ((sg (3))))))
			      (vgfc ((c1 c2 c4) (imperfekt ((pl (2))))))
			      (vgfd (konjunktiv-2 ((pl (2))))))
			   (7 (vgfa ((a1 a4) (praesens ((pl (2))))
				     (imperativ (pl))))
			      (vgfb ((b1 b7) (praesens ((sg (3)))))
				    (b4 (praesens ((sg (2 3))))))
			      (vgfc ((c1 c2) (imperfekt ((pl (2))))))
			      (vgfd (konjunktiv-2 ((pl (2))))))
			   (8 (vgfa (a1 (praesens ((pl (2))))
					(imperativ (pl)))))
			   (9 (vgfa ((a1 a4) (praesens ((pl (2))))
				     (imperativ (pl))))
			      (vgfb (b6 (praesens ((sg (2))))))
			      (vgfc (c4 (imperfekt ((pl (2)))))))
			   (10 (vgfa ((a1 a4) (praesens ((pl (2))))
				      (imperativ (pl))))
			       (vgfb (b6 (praesens ((sg (2))))))
			       (vgfc (c4 (imperfekt ((pl (2))))))
			       (vgfd (imperfekt ((pl (2))))
				     (konjunktiv-2 ((pl (2))))))
			   (11 (vgfc (c1 (imperfekt ((pl (2))))))
			       (vgfd (konjunktiv-2 ((pl (2))))))))
	       (ordinalzahl (t 5)))
	 (#\e (info "et" "t")
	  (root (verb (partizip pprf)
		      (vtyp (1 (vgfa ((a1 a3 a4) (konjunktiv-1 ((pl (2)))))
				     (a2 (praesens ((sg (3)) (pl (2))))
					 (imperativ (pl))
					 (konjunktiv-1 ((pl (2)))))))
			    (2 (vgfa (a1 (konjunktiv-1 ((pl (2)))))
				     (a2 (praesens ((sg (3)) (pl (2))))
					 (imperativ (pl))
					 (konjunktiv-1 ((pl (2)))))))
			    (3 (vgfa ((a1 a4) (konjunktiv-1 ((pl (2)))))
				     (a2 (praesens ((sg (3)) (pl (2))))
					 (imperativ (pl))
					 (konjunktiv-1 ((pl (2))))))
			       (vgfc ((c1 c2) (konjunktiv-2 ((pl (2)))))
				     (c3 (imperfekt ((pl (2))))
					 (konjunktiv-2 ((pl (2)))))))
			    (4 (vgfa ((a1 a4) (konjunktiv-1 ((pl (2)))))
				     (a2 (praesens ((sg (3)) (pl (2))))
					 (imperativ (pl))
					 (konjunktiv-1 ((pl (2))))))
			       (vgfc (c3 (imperfekt ((pl (2)))))))
			    (5 (vgfa ((a1 a4) (konjunktiv-1 ((pl (2)))))
				     (a2 (praesens ((pl (2))))
					 (imperativ (pl))
					 (konjunktiv-1 ((pl (2))))))
			       (vgfc ((c1 c2) (konjunktiv-2 ((pl (2)))))
				     (c3 (imperfekt ((pl (2))))
					 (konjunktiv-2 ((pl (2)))))))
			    (6 (vgfa (a1 (konjunktiv-1 ((pl (2)))))
				     (a4 (konjunktiv-1 ((sg (3)) (pl (2)))))
				     (a2 (praesens ((pl (2))))
					 (imperativ (pl))
					 (konjunktiv-1 ((pl (2))))))
			       (vgfc (c3 (imperfekt ((pl (2)))))))
			    (7 (vgfa ((a1 a4) (konjunktiv-1 ((pl (2)))))
				     (a2 (praesens ((pl (2))))
					 (imperativ (pl))
					 (konjunktiv-1 ((pl (2))))))
			       (vgfc (c3 (imperfekt ((pl (2)))))))
			    (8 (vgfa (a1 (konjunktiv-1 ((pl (2)))))))
			    (9 (vgfa ((a1 a4) (konjunktiv-1 ((pl (2)))))))
			    (10 (vgfa ((a1 a4) (konjunktiv-1 ((pl (2)))))))
			    (11 (vgfa (a7 (konjunktiv-1 ((pl (2))))))))))
	  (#\t (info "tet" "et" "t")
	   (root (verb (vtyp (1 (vgfa ((a1 a3 a4 a5 a6)
				       (imperfekt ((pl (2))))
				       (konjunktiv-2 ((pl (2)))))))
			     (2 (vgfa (a1 (konjunktiv-2 ((pl (2)))))))
			     (8 (vgfa (a1 (imperfekt ((pl (2))))
					  (konjunktiv-2 ((pl (2)))))))
			     (9 (vgfa ((a1 a4) (konjunktiv-2 ((pl (2))))))))))
	   (#\e (info "etet" "tet" "et" "t")
	    (root (verb (vtyp ((1 2) (vgfa (a2 (imperfekt ((pl (2))))
					       (konjunktiv-2 ((pl (2)))))))))))))
	 (#\s (info "st" "t")
	  (root (adjektiv ((a1 b1) (t ((red+uml+ red-uml- red+uml0 red-uml0)
				       ((t nec pos) (st ((t pred-e) (sup 5))))))))
		(verb (vtyp (1 (vgfa ((a1 a3) (praesens ((sg (2)))))
				     ((a5 a6) (praesens ((sg (2))))
				      (konjunktiv-1 ((sg (2)))))))
			    (2 (vgfa (a1 (praesens ((sg (2))))))
			       (vgfc (c4 (imperfekt ((sg (2)))))))
			    (3 (vgfa (a1 (praesens ((sg (2))))))
			       (vgfc ((c1 c3) (imperfekt ((sg (2)))))
				     (c4 (imperfekt ((sg (2))))
					 (konjunktiv-2 ((sg (2)))))))
			    (4 (vgfa (a1 (praesens ((sg (2)))))
				     (a7 (praesens ((sg (2))))
					 (konjunktiv-1 ((sg (2))))))
			       (vgfc ((c1 c3 c4) (imperfekt ((sg (2))))))
			       (vgfd (konjunktiv-2 ((sg (2))))))
			    (5 (vgfb ((b1 b3) (praesens ((sg (2))))))
			       (vgfc ((c1 c3) (imperfekt ((sg (2)))))))
			    (6 (vgfb ((b1 b3 b5) (praesens ((sg (2))))))
			       (vgfc ((c1 c3 c4) (imperfekt ((sg (2))))))
			       (vgfd (konjunktiv-2 ((sg (2))))))
			    (7 (vgfb ((b1 b3 b7) (praesens ((sg (2))))))
			       (vgfc (c1 (imperfekt ((sg (2))))))
			       (vgfd (konjunktiv-2 ((sg (2))))))
			    (8 (vgfb (b3 (praesens ((sg (2)))))))
			    (9 (vgfb (b3 (praesens ((sg (2))))))
			       (vgfc (c4 (imperfekt ((sg (2)))))))
			    (10 (vgfb (b3 (praesens ((sg (2))))))
				(vgfc (c4 (imperfekt ((sg (2))))))
				(vgfd (konjunktiv-2 ((sg (2))))))
			    (11 (vgfa (a7 (konjunktiv-1 ((sg (2))))))
				(vgfc (c1 (imperfekt ((sg (2))))))
				(vgfd (konjunktiv-2 ((sg (2))))))))
		(ordinalzahl (st 5)))
	  (#\e (info "est" "st" "t")
	   (root (adjektiv ((a1 b1) (t ((red+uml+ red-uml- red+uml0 red-uml0)
					((t nec pos) (est ((t pred-e) (sup 5))))))))
		 (verb (vtyp (1 (vgfa ((a1 a3 a4)
				       (konjunktiv-1 ((sg (2)))))
				      (a2 (praesens ((sg (2))))
					  (konjunktiv-1 ((sg (2)))))))
			     (2 (vgfa (a1 (konjunktiv-1 ((sg (2)))))
				      (a2 (praesens ((sg (2))))
					  (konjunktiv-1 ((sg (2)))))))
			     (3 (vgfa ((a1 a4) (konjunktiv-1 ((sg (2)))))
				      (a2 (praesens ((sg (2))))
					  (konjunktiv-1 ((sg (2))))))
				(vgfc ((c1 c4) (konjunktiv-2 ((sg (2)))))
				      ((c2 c3)
				       (imperfekt ((sg (2))))
				       (konjunktiv-2 ((sg (2)))))))
			     (4 (vgfa ((a1 a4) (konjunktiv-1 ((sg (2)))))
				      (a2 (praesens ((sg (2))))
					  (konjunktiv-1 ((sg (2))))))
				(vgfc ((c2 c3) (imperfekt ((sg (2)))))))
			     (5 (vgfa ((a1 a2 a4) (konjunktiv-1 ((sg (2))))))
				(vgfc (c1 (konjunktiv-2 ((sg (2)))))
				      ((c2 c3)
				       (imperfekt ((sg (2))))
				       (konjunktiv-2 ((sg (2)))))))
			     (6 (vgfa ((a1 a2 a4) (konjunktiv-1 ((sg (2))))))
				(vgfc ((c2 c3) (imperfekt ((sg (2)))))))
			     (7 (vgfa ((a1 a2 a4) (konjunktiv-1 ((sg (2))))))
				(vgfc ((c2 c3) (imperfekt ((sg (2)))))))
			     (8 (vgfa (a1 (konjunktiv-1 ((sg (2)))))))
			     ((9 10) (vgfa ((a1 a4) (konjunktiv-1 ((sg (2)))))))
			     (11 (vgfa (a7 (konjunktiv-1 ((sg (2))))))))))
	   (#\t (info "test" "est" "st" "t")
	    (root (verb (weg "t" "est")
			(vtyp (1 (vgfa ((a1 a3 a4 a5 a6)
					(imperfekt ((sg (2))))
					(konjunktiv-2 ((sg (2)))))))
			      (2 (vgfa (a1 (konjunktiv-2 ((sg (2)))))))
			      (8 (vgfa (a1 (imperfekt ((sg (2))))
					   (konjunktiv-2 ((sg (2)))))))
			      (9 (vgfa ((a1 a4) (konjunktiv-2 ((sg (2))))))))))
	    (#\e (info "etest" "test" "est" "st" "t")
	     (root (verb (vtyp ((1 2) (vgfa (a2 (imperfekt ((sg (2))))
						(konjunktiv-2 ((sg (2)))))))))))))
	  (#\n
	   (#\e (info "enst" "st" "t")
	    (root (verb (weg "en" "st")))))
	  (#\t (info "tst" "st" "t")
	   (root (verb (weg "t" "st")))
	   (#\e (info "etst" "st" "t")
	    (root (verb (weg "et" "st")))))
	  (#\d
	   (#\n (info "ndst" "st" "t")
	    (root (verb (weg "nd" "st")))
	    (#\e (info "endst" "st" "t")
	     (root (verb (weg "end" "st")))))))
	 
	 )
	(#\m (info "m")
	 (root (possessivpronomen
		(2 (sg+pl
		    (substantivwort
		     ((ohne ((mas ((sg (dat))))
			     (ntr ((sg (dat))))))))
		    (artikelwort
		     ((mas ((sg (dat)))) (ntr ((sg (dat))))))))))
	 (#\e (info "em")
	  (root
	   (adjektiv (a1 (t ((red-uml+ red-uml- red-uml0)
			     ((t pos) ((st est irreg) ((t pred-e) (pos 3))))))
			 (elision (red-uml-
				   ((nec pos) ((st est) ((t pred-e) (pos 3))))))
			 (pos (red-uml-
			       (t (irreg-pos ((t pred-e) (pos 3))))))
			 (kom (red-uml-
			       (t ((irreg irreg-pos) ((t pred-e) (kom 3))))))
			 (sup (red-uml-
			       (t ((irreg irreg-pos) ((t pred-e) (sup 3)))))))
		     (b1 (t ((red-uml+ red-uml- red-uml0)
			     ((t pos) ((st est) ((t pred-e) (pos 3))))))
			 (elision (red-uml-
				   ((nec pos) ((st est) ((t pred-e) (pos 3)))))))
		     ((a2 b2)
		      (t (red-uml-
			  ((t pos) ((st est irreg nil) ((t pred-e) (pos 3))))))
		      (elision (red-uml-
				((nec pos) ((st est nil) ((t pred-e) (pos 3))))))
		      (pos (red-uml-
			    (t (irreg-pos ((t pred-e) (pos 3))))))))
	   ((possessivpronomen determinativ determinativ-indef)
	    ((1 2 3)
	     ((sg+pl sg)
	      (substantivwort
	       ((ohne ((mas ((sg (dat))))
		       (ntr ((sg (dat))))))))
	      (artikelwort
	       ((mas ((sg (dat)))) (ntr ((sg (dat)))))))))
	   (ordinalzahl ((ordinal ordinal-b no) 3)))
	  (#\d
	   (#\n (info "ndem" "em")
	    (root (verb (weg "nd" "em")))
	    (#\e (info "endem" "em")
	     (root (verb (weg "end" "em"))))))
	  (#\r
	   (#\e (info "erem" "em")
	    (root (adjektiv (a1 (t ((red+uml+ red-uml- red+uml0 red-uml0)
				    ((t pos) ((st est) ((t pred-e) (kom 3))))))
				(elision (red-uml-
					  ((nec pos) ((st est) ((t pred-e) (kom 3)))))))))
	    (#\d
	     (#\n (info "nderem" "erem" "em")
	      (root (verb (weg "nd" "erem")))
	      (#\e (info "enderem" "erem" "em")
	       (root (verb (weg "end" "erem"))))))
	    (#\t (info "terem" "erem" "em")
	     (root (verb (weg "t" "erem")))
	     (#\e (info "eterem" "terem" "erem" "em")
	      (root (verb (weg "et" "erem")))))
	    (#\n (#\e (info "enerem" "erem" "em")
		  (root (verb (weg "en" "erem")))))))
	  (#\t (info "tem" "em")
	   (root (verb (weg "t" "em"))
		 (ordinalzahl (t 3)))
	   (#\s (info "stem" "tem" "em") ; hierix
	    (root (adjektiv ((a1 b1) (t ((red+uml+ red-uml- red+uml0 red-uml0)
					 ((t nec pos) (st ((t pred-e) (sup 3))))))))
		  (ordinalzahl (st 3)))
	    (#\d
	     (#\n (info "ndstem" "stem" "em")
	      (root (verb (weg "nd" "stem")))
	      (#\e (info "endstem" "stem" "em")
	       (root (verb (weg "end" "stem"))))))
	    (#\t (info "tstem" "stem" "em")
	     (root (verb (weg "t" "stem")))
	     (#\e (info "etstem" "tstem" "stem" "em")
	      (root (verb (weg "et" "stem")))))
	    (#\n
	     (#\e (info "enstem" "stem" "em")
	      (root (verb (weg "en" "stem")))))
	    (#\e (info "estem" "stem" "tem" "em")
	     (root (adjektiv ((a1 b1) (t ((red+uml+ red-uml- red+uml0 red-uml0)
					  ((t nec pos) (est ((t pred-e) (sup 3)))))))))
	     (#\t (info "testem" "estem" "em")
	      (root (verb (weg "t" "estem"))))))
	   (#\e (info "etem" "tem" "em")
	    (root (verb (weg "et" "em")))))
	  (#\n (info "nem" "em")
	   (root (verb (weg "n" "em")))
	   (#\e (info "enem" "em")
	    (root (verb (weg "en" "em"))))))
	 
	 )
	(#\d (info "d")
	 (root (verb (vtyp (6 (vgfb (b5 (praesens ((sg (3)))))))
			   (11 (vgfa (a7 (praesens ((pl (2))))
					 (imperativ (pl))))))))
	 (#\n (info "nd")
	  (root (verb (partizip (vgfa ((a5 a6) (pprs))))))
	  (#\e (info "end" "nd")
	   (root (verb (partizip (vgfa ((a1 a2 a3 a4 a7) (pprs)))))))))))

